"""Generate JSON contract fixtures for the operator-surface projection.

PRD #607 / Slice 1 (#608) — contract-test bridge between the Python
``operator_surface`` projection and the Frontend ``LiveInstanceStatus``
TypeScript type.  Captures real status responses for each of the
cockpit fixtures (STEADY / CONFIGURE / BLOCKED / TRIAGE) into
``Frontend/src/testing/operator_surface_fixtures/<state>.json``.  The
Frontend then imports each fixture and asserts ``payload satisfies
LiveInstanceStatus`` — a shape mismatch becomes a TypeScript build
failure.

This script is intentionally standalone so it can be re-run after any
projection change and committed alongside the Python diff that triggered
the fixture refresh.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace
from typing import Any

from httpx import ASGITransport, AsyncClient

from app.engine.live import host_daemon_client
from app.engine.live.daemon_transport import DaemonResult
from app.routers import live_instances

_REPO_ROOT = Path(__file__).resolve().parents[2]
_FIXTURE_DIR = (
    _REPO_ROOT / "Frontend" / "src" / "testing" / "operator_surface_fixtures"
)
_FIXTURE_TS = _FIXTURE_DIR / "live-instance-status.fixtures.ts"
_FIXTURE_NOW_MS = 1_782_000_000_000
_FIXTURE_ROOT_TOKEN = "__OPERATOR_SURFACE_FIXTURE_ROOT__"


def _write_ledger(root: Path, run_id: str, sid: str, created_at_ms: int) -> None:
    run_dir = root / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "run_ledger.json").write_text(
        json.dumps(
            {
                "run_id": run_id,
                "strategy_instance_id": sid,
                "created_at_ms": created_at_ms,
            }
        ),
        encoding="utf-8",
    )


def _sanitize_fixture_payload(payload: Any, root: Path) -> Any:
    if isinstance(payload, dict):
        return {key: _sanitize_fixture_payload(value, root) for key, value in payload.items()}
    if isinstance(payload, list):
        return [_sanitize_fixture_payload(value, root) for value in payload]
    if isinstance(payload, str):
        return payload.replace(str(root), _FIXTURE_ROOT_TOKEN)
    return payload


def _ts_fixture_name(name: str) -> str:
    parts = [part for part in name.replace("-", "_").split("_") if part]
    return parts[0] + "".join(part.capitalize() for part in parts[1:]) + "Fixture"


def _write_typescript_fixtures(fixtures: dict[str, dict[str, Any]]) -> None:
    lines = [
        "// Auto-generated by PythonDataService/scripts/capture_operator_surface_fixture.py.",
        "// Do not edit by hand; refresh fixtures from the Python status route.",
        "",
        "import type { LiveInstanceStatus } from '../../app/api/live-instances.types';",
        "",
        "type DeepReadonly<T> = T extends (...args: never[]) => unknown",
        "  ? T",
        "  : T extends readonly (infer Item)[]",
        "    ? readonly DeepReadonly<Item>[]",
        "    : T extends object",
        "      ? { readonly [Key in keyof T]: DeepReadonly<T[Key]> }",
        "      : T;",
        "",
    ]
    for name, payload in fixtures.items():
        fixture_name = _ts_fixture_name(name)
        fixture_json = json.dumps(payload, indent=2, sort_keys=True)
        lines.append(
            f"export const {fixture_name} = {fixture_json} as const "
            "satisfies DeepReadonly<LiveInstanceStatus>;"
        )
        lines.append("")
    _FIXTURE_TS.write_text("\n".join(lines), encoding="utf-8")


async def _capture(state: str, process: dict[str, Any] | None) -> dict[str, Any]:
    with TemporaryDirectory(prefix=f"operator-surface-{state}-") as tmp_name:
        tmp = Path(tmp_name)
        stub = SimpleNamespace(
            live_runs_root=str(tmp / "live_runs"),
            live_runner_daemon_url="http://daemon",
            live_runner_host_start_command="python -m app.engine.live.host_daemon",
            fleet_dirty_blocks_starts=False,
            mode="paper",
            readonly=False,
        )
        (tmp / "live_runs").mkdir(parents=True, exist_ok=True)
        _write_ledger(tmp / "live_runs", f"run-{state}", "spy_ema_paper", 100)

        monkeyed_settings = live_instances.get_settings
        live_instances.get_settings = lambda: stub  # type: ignore[assignment]
        monkeyed_now_ms = live_instances._now_ms
        live_instances._now_ms = lambda: _FIXTURE_NOW_MS  # type: ignore[assignment]

        async def fake_process(_base_url: str, _sid: str) -> tuple[DaemonResult, dict | None]:
            return DaemonResult(kind="CONNECTED"), process

        monkeyed_fetch = host_daemon_client.fetch_instance_process
        host_daemon_client.fetch_instance_process = fake_process  # type: ignore[assignment]
        try:
            from app.main import app

            async with AsyncClient(
                transport=ASGITransport(app=app), base_url="http://test"
            ) as client:
                response = await client.get("/api/live-instances/spy_ema_paper/status")
            response.raise_for_status()
            return _sanitize_fixture_payload(response.json(), tmp)
        finally:
            live_instances.get_settings = monkeyed_settings  # type: ignore[assignment]
            live_instances._now_ms = monkeyed_now_ms  # type: ignore[assignment]
            host_daemon_client.fetch_instance_process = monkeyed_fetch  # type: ignore[assignment]


async def main() -> None:
    _FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    fixture_processes = {
        "steady": {
            "state": "running",
            "run_id": "run-steady",
            "pid": 99,
            "started_at_ms": 100,
        },
        "stopped": {"state": "idle"},
    }
    captured_fixtures: dict[str, dict[str, Any]] = {}
    for name, process in fixture_processes.items():
        payload = await _capture(name, process)
        captured_fixtures[name] = payload
        target = _FIXTURE_DIR / f"{name}.json"
        target.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        print(f"wrote {target}")
    _write_typescript_fixtures(captured_fixtures)
    print(f"wrote {_FIXTURE_TS}")


if __name__ == "__main__":
    asyncio.run(main())
