"""Regenerate cross-engine golden-fixture cells.

Per-cell sequence (Task 7 ships the orchestration shape; Task 10 fills
the LEAN/Engine staging stubs):

  1. Pre-flight: verify _lean_data_capture/<TICKER>/ exists and its
     data_contract_hash matches the capture manifest.
  2. Stage LEAN sidecar run for (ticker, window) into a temp dir.
  3. Run Engine Lab live against the same capture, into another temp dir.
  4. Run all three gates via run_cell_gates.
  5. On pass: write reconciliation_pinned.json, replace the committed
     cell directory atomically, update manifest.json with new artifact
     hashes.
  6. On fail: emit failure report to a sibling .failed/ dir; exit
     non-zero; leave committed cell directory untouched.

Reference: docs/superpowers/specs/2026-05-21-cross-engine-golden-matrix-design.md
            § "Regeneration workflow"
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

from app.lean_sidecar.parity_matrix.cell_runner import (
    CellRunReport,
    run_cell_gates,
)
from app.lean_sidecar.parity_matrix.matrix import CELLS, Cell, cell_by_id

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = REPO_ROOT / "PythonDataService" / "tests" / "fixtures" / "golden" / "cross-engine-studies"


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Regenerate cross-engine golden-fixture cells.")
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--all", action="store_true", help="Regenerate all 12 cells.")
    group.add_argument("--cell", type=str, help="Regenerate one cell by cell_id.")
    group.add_argument(
        "--ticker",
        type=str,
        help="Regenerate all three cells for one ticker.",
    )
    return p.parse_args(argv)


def _resolve_target_cells(ns: argparse.Namespace) -> list[Cell]:
    """Resolve the CLI namespace to a list of Cells to regenerate.

    Raises KeyError when ``--cell`` names an unknown cell. Returns empty
    list for an unknown ``--ticker`` — main() decides whether to error.
    """
    if ns.all:
        return list(CELLS)
    if ns.cell:
        return [cell_by_id(ns.cell)]
    if ns.ticker:
        return [c for c in CELLS if c.ticker == ns.ticker]
    raise SystemExit("no target specified")


def _stage_lean_run(cell: Cell, output_dir: Path) -> None:
    """Run LEAN sidecar for one cell; write outputs to output_dir/lean/.

    Stub — filled in Task 10 after Polygon captures exist (Task 9).
    """
    raise NotImplementedError("Task 10: wire to app.lean_sidecar.runner + workspace + trusted-sample staging")


def _run_engine_live(cell: Cell, output_dir: Path) -> list:
    """Run Engine Lab via cross_runner; write outputs to output_dir/engine/.

    Returns the normalized order events for Gate 3.

    Stub — filled in Task 10.
    """
    raise NotImplementedError("Task 10: wire to app.lean_sidecar.cross_runner.run_engine_lab_on_workspace")


def _build_manifest_dict(cell: Cell, staging: Path) -> dict:
    """Build the manifest payload with fresh artifact hashes.

    Stub — filled in Task 10 after the trusted-sample source-sha, LEAN
    image digest, and capture data_contract_hash are all reachable.
    """
    raise NotImplementedError("Task 10: build CellManifest with sha256_of_text(EMA_CROSSOVER_SOURCE) etc.")


def _write_cell_atomically(
    *,
    cell: Cell,
    staged_lean_dir: Path,
    reconciliation: dict,
) -> None:
    """Replace the committed cell directory in one rename; write
    manifest.json + attribution.md + reconciliation_pinned.json.
    """
    target = FIXTURE_ROOT / "cells" / cell.cell_id
    staging = FIXTURE_ROOT / "cells" / f".{cell.cell_id}.new"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)

    shutil.copytree(staged_lean_dir, staging / "lean")
    (staging / "reconciliation_pinned.json").write_text(
        json.dumps(reconciliation, indent=2, sort_keys=True),
        encoding="utf-8",
    )

    manifest_dict = _build_manifest_dict(cell, staging)
    (staging / "manifest.json").write_text(
        json.dumps(manifest_dict, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    (staging / "attribution.md").write_text(
        f"# {cell.cell_id} attribution\n\n"
        f"Regenerated by `regenerate_cross_engine_study.py`. "
        f"See `manifest.json` for the full provenance block.\n",
        encoding="utf-8",
    )

    if target.exists():
        shutil.rmtree(target)
    staging.rename(target)


def _emit_failure_report(cell: Cell, report: CellRunReport, root: Path) -> None:
    """Write a JSON failure report under root/.failed/<cell_id>/."""
    failure_dir = root / ".failed" / cell.cell_id
    failure_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "cell_id": cell.cell_id,
        "overall_passed": report.overall_passed,
        "observations_passed": report.observations.passed,
        "state_passed": (report.state.passed if report.state is not None else None),
        "trade_passed": (report.trade.passed if report.trade is not None else None),
        "observations_failures": [
            {"row_index": f.row_index, "field": f.field, "reason": f.reason} for f in report.observations.failures
        ],
        "state_failures": (
            [
                {
                    "row_index": f.row_index,
                    "field": f.field,
                    "reason": f.reason,
                }
                for f in report.state.failures
            ]
            if report.state is not None
            else None
        ),
    }
    (failure_dir / "report.json").write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def regenerate_one_cell(cell: Cell) -> bool:
    """Regenerate one cell. Returns True on pass, False on fail."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        lean_out = tmp_root / "lean_staged"
        lean_out.mkdir()
        eng_out = tmp_root / "engine_staged"
        eng_out.mkdir()

        _stage_lean_run(cell, lean_out)
        engine_orders = _run_engine_live(cell, eng_out)

        report = run_cell_gates(
            pinned_lean_dir=lean_out / "lean",
            engine_output_dir=eng_out / "engine",
            engine_normalized_orders=engine_orders,
        )

        if not report.overall_passed:
            _emit_failure_report(cell, report, FIXTURE_ROOT)
            return False

        reconciliation = {
            "status": "passed",
            "trade_summary": (
                {
                    "passed": report.trade.passed,
                    "gating_divergent_count": getattr(report.trade, "gating_divergent_count", None),
                }
                if report.trade is not None
                else None
            ),
            "captured_at_ms_utc": int(datetime.now(UTC).timestamp() * 1000),
        }
        _write_cell_atomically(
            cell=cell,
            staged_lean_dir=lean_out / "lean",
            reconciliation=reconciliation,
        )
        return True


def main(argv: list[str] | None = None) -> int:
    ns = _parse_args(argv if argv is not None else sys.argv[1:])
    cells = _resolve_target_cells(ns)
    if not cells:
        print("No cells matched the selection.", file=sys.stderr)
        return 2
    print(f"Regenerating {len(cells)} cell(s): {[c.cell_id for c in cells]}")
    failures: list[str] = []
    for c in cells:
        print(f"--- {c.cell_id} ---")
        if regenerate_one_cell(c):
            print("  passed")
        else:
            failures.append(c.cell_id)
            print(
                f"  FAILED — see .failed/{c.cell_id}/report.json",
                file=sys.stderr,
            )
    if failures:
        print(f"\n{len(failures)} cell(s) failed: {failures}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
