"""Run the golden-trace qualification job and emit Signal Program build receipts.

PRD `docs/prds/sealed-signal-program-to-governed-alpaca-bot.md` S11.4 requires
that Start and Resume load "a compatibility receipt generated by the
golden-trace qualification job" and states plainly that "CI failure alone is
not an admission control." Before this command existed,
``app/data/signal_program_build_receipts.json`` was hand-authored: nothing
actually re-ran the golden corpus before a receipt was stamped, so a program
edit that forgot to bump ``program_version``/``golden_trace_root`` could still
end up with a committed receipt that looked legitimate.

This command closes that gap. For every registered Signal Program listed in
``_QUALIFICATION_SUITES`` it:

1. runs that program's golden-trace qualification pytest as a subprocess —
   the same test that replays the validated-settings corpus and pins its
   trace root (``tests/engine/strategy/test_ema_signal_program.py``); and
2. only on a clean pass, hashes the currently loaded artifact bytes
   (``app.services.signal_program_admission.running_artifact_digest``) and
   emits a receipt binding that digest to the registry's sealed
   ``(program_version, golden_trace_root)``.

A qualification failure raises before any receipt is written or updated, so a
behavior change without the matching version/root bump cannot produce
admissible runtime evidence — it leaves the prior, now digest-mismatched
receipt in place, and ``prove_running_program_build`` fails closed with
``PROGRAM_BUILD_UNPROVEN`` at Start/Resume.

Usage::

    python -m scripts.run_signal_program_build_qualification
    python -m scripts.run_signal_program_build_qualification --check

Re-running with unchanged code is a byte-for-byte no-op: a receipt whose
(program_key, program_version, golden_trace_root, artifact_digest,
qualification_suite) tuple already matches the committed manifest keeps its
original ``qualified_at_ms`` rather than mint a new one, mirroring the golden
fixture lifecycle rule ("regenerated only with justification").
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from app.engine.strategy.registry import _STRATEGY_REGISTRY
from app.services.signal_program_admission import (
    DEFAULT_QUALIFICATION_MANIFEST,
    ProgramBuildQualificationManifest,
    qualification_receipt_payload,
    running_artifact_digest,
)
from app.utils.atomic_file import atomic_write_bytes
from app.utils.timestamps import now_ms_utc

_SERVICE_ROOT = Path(__file__).resolve().parents[1]
_PYTEST_TIMEOUT_SECONDS = 300

# Every `_STRATEGY_REGISTRY` entry with a `signal_program_contract` and a
# `signal_program_factory` is a Signal Program whose running bytes require
# build proof at Start/Resume (see
# `app/services/signal_program_admission.py::prove_running_program_build`).
# Only a program listed here — naming the pytest node id that replays its own
# golden trace corpus — can gain admissible evidence from this command.
#
# `ema_crossover_2_bps` and `spy_ema_crossover` are NOT registered Signal
# Programs: `app/engine/strategy/registry.py` explicitly sets both their
# `signal_program_contract` and `signal_program_factory` to `None` (issue
# #1728 defect 1 — they used to inherit EMA's via `dataclasses.replace`,
# which let them falsely claim EMA's `golden_trace_root` and permanently
# bricked Start/Resume, since no receipt in the manifest could ever match
# `binding.strategy_key` for either). `prove_running_program_build` treats an
# unregistered Signal Program as `NOT_APPLICABLE` rather than `UNPROVEN`, so
# both keep working on their existing (non-Signal-Program) execution path.
# Promoting either to a real, independently golden-qualified Signal Program
# is issue #1730 / Slice 5 — add its own entry here, with its own corpus,
# when that lands.
_QUALIFICATION_SUITES: dict[str, str] = {
    "ema_crossover_signal": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[ema_crossover_signal]"
    ),
    "sma_crossover": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[sma_crossover]"
    ),
    "rsi_mean_reversion": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[rsi_mean_reversion]"
    ),
    "spy_strategy_a": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[spy_strategy_a]"
    ),
    "spy_strategy_b": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[spy_strategy_b]"
    ),
    "spy_strategy_c": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[spy_strategy_c]"
    ),
    "deployment_validation": (
        "tests/engine/strategy/test_signal_program_qualification_matrix.py::test_validated_settings_corpus_has_a_pinned_trace_root"
        "[deployment_validation]"
    ),
}

# --- Signal-decision digest closure (issue #1728 defect 2) ----------------
#
# `SignalProgramContract.artifact_paths` is not "every file the module graph
# reaches from the declared roots" — it is that transitive first-party
# import closure MINUS the files below, each proven unable to change an
# `EvaluationTrace` (`app/engine/strategy/signal_program.py`).
# `SignalSession.advance()` builds and stores the trace from
# `evaluate_signal_bar()`'s return value *before* `settle()` ever calls
# `commit_signal_decision()`, so anything reached only through the commit
# path — fills, sizing, portfolio, commission, Insight publication — cannot
# retroactively change a trace that already exists by the time it runs.
#
# `tests/engine/strategy/test_signal_decision_digest_closure.py` recomputes
# the closure from the registered `artifact_paths` and asserts
# ``closure - exclusions == artifact_paths`` exactly, so a newly introduced
# import must be explicitly triaged into one bucket or the other — silent
# drift in either direction fails the build.
_SHARED_EXECUTION_BOUNDARY_EXCLUSIONS: dict[str, str] = {
    "app/engine/execution/commission.py": (
        "Commission/fee model; consulted only when pricing a fill, never inside evaluate_signal_bar()'s decision math."
    ),
    "app/engine/execution/order.py": (
        'Direction/OrderEvent are read only by on_order_event(), which runs after a fill and only appends to the trade log — the trace for that bar is already built and immutable by then.'
    ),
    "app/engine/execution/signal_intent_executor.py": (
        'Referenced only under `if TYPE_CHECKING:` in strategy/base.py — never imported at runtime — and its concrete executors translate an already-decided SignalIntent into broker actions after the trace exists.'
    ),
    "app/engine/execution/sizing.py": (
        'Share/notional sizing math belongs to the execution boundary that sizes an already-decided trade; never consulted for entry/exit facts.'
    ),
    "app/engine/framework/insight_scorer.py": (
        'Scores Insight objects for the Alpha framework; never consulted by evaluate_signal_bar().'
    ),
    "app/research/parity/ibkr_commission.py": (
        'IBKR fee-tier table reached only through execution/commission.py; same fee-only reasoning.'
    ),
}


def _closure_exclusions(*, portfolio: str, insight: str, insight_manager: str) -> dict[str, str]:
    """One program's triage: the shared execution-boundary reasons plus the
    three whose wording is genuinely program-specific (they name the class
    that does or does not reach the file).

    Six programs previously restated all nine entries. Six of the nine
    carried byte-identical prose, so a correction to any of them had to be
    made six times, and nothing would have caught the sixth being missed --
    it is documentation, not an assertion.
    """
    return {
        **_SHARED_EXECUTION_BOUNDARY_EXCLUSIONS,
        "app/engine/execution/portfolio.py": portfolio,
        "app/engine/framework/insight.py": insight,
        "app/engine/framework/insight_manager.py": insight_manager,
    }


_EMA_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only bar.close, never portfolio state, to compute its facts.',
    insight='Insight/InsightDirection are constructed inside commit_signal_decision(), which advance() calls only after _build_trace() has already produced the immutable EvaluationTrace.',
    insight_manager='Reached only via StrategyContext.emit_insight(), called from commit_signal_decision() after the trace for that bar already exists.',
)

# Same triage, for `sma_crossover`'s own closure (issue #1730 Slice 5). The
# roots differ (no RSI/EMA indicators, no Insight emission from
# SmaCrossoverAlgorithm.commit_signal_decision), but every excluded file
# below is reached the same way EMA's is: through app/engine/strategy/base.py
# and app/engine/execution/*'s own general, strategy-agnostic imports, never
# from evaluate_signal_bar()'s decision math.
_SMA_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only bar.close, never portfolio state, to compute its facts.',
    insight="Reached via strategy/base.py's StrategyContext.emit_insight() plumbing, which SmaCrossoverAlgorithm.commit_signal_decision never calls — and even where a program does call it, that only happens after _build_trace() has already produced the immutable EvaluationTrace.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by SmaCrossoverAlgorithm; not consulted by evaluate_signal_bar() either way.',
)

# Same triage, for `rsi_mean_reversion`'s own closure (issue #1730 Slice 5).
# The roots differ (a single RSI series, no crossover-state seeding), but
# every excluded file below is reached the same way EMA's and SMA's are:
# through app/engine/strategy/base.py and app/engine/execution/*'s own
# general, strategy-agnostic imports, never from evaluate_signal_bar()'s
# decision math.
_RSI_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only bar.close, never portfolio state, to compute its facts.',
    insight="Reached via strategy/base.py's StrategyContext.emit_insight() plumbing, which RsiMeanReversionAlgorithm.commit_signal_decision never calls — and even where a program does call it, that only happens after _build_trace() has already produced the immutable EvaluationTrace.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by RsiMeanReversionAlgorithm; not consulted by evaluate_signal_bar() either way.',
)

# Same triage, for `spy_strategy_a`'s own closure (issue #1730 Slice 5). The
# roots are the two files that hold its decision math -- spy_strategy_a.py
# and the shared _rsi_range_base.py it extends -- and every excluded file
# below is reached the same way EMA's and SMA's are: through
# app/engine/strategy/base.py and app/engine/execution/*'s own general,
# strategy-agnostic imports, never from evaluate_signal_bar()'s decision
# math.
_SPY_STRATEGY_A_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only bar.close (and bar.high/bar.low for ADX), never portfolio state, to compute its facts.',
    insight="Reached via strategy/base.py's StrategyContext.emit_insight() plumbing, which RsiRangeStrategy.commit_signal_decision never calls — and even where a program does call it, that only happens after _build_trace() has already produced the immutable EvaluationTrace.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by RsiRangeStrategy/SpyStrategyAAlgorithm; not consulted by evaluate_signal_bar() either way.',
)

# Same triage, for `spy_strategy_b`'s own closure (issue #1730 Slice 5, first
# RSI-range-family promotion). The roots are
# app/engine/strategy/algorithms/spy_strategy_b.py AND
# app/engine/strategy/algorithms/_rsi_range_base.py — the custody-split
# methods (evaluate_signal_bar/commit_signal_decision/discard_signal_decision)
# live on the shared base, inherited by SpyStrategyBAlgorithm rather than
# redeclared. Every excluded file below is reached the same way EMA's and
# SMA's are: through app/engine/strategy/base.py and app/engine/execution/*'s
# own general, strategy-agnostic imports, never from
# evaluate_signal_bar()'s decision math.
_SPY_STRATEGY_B_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only bar.close, never portfolio state, to compute its facts.',
    insight="Reached via strategy/base.py's StrategyContext.emit_insight() plumbing, which RsiRangeStrategy.commit_signal_decision never calls — and even where a program does call it, that only happens after _build_trace() has already produced the immutable EvaluationTrace.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by RsiRangeStrategy/SpyStrategyBAlgorithm; not consulted by evaluate_signal_bar() either way.',
)

# Same triage, for `spy_strategy_c`'s own closure (issue #1730 Slice 5,
# second additional promotion). Its decision math lives on the shared
# `RsiRangeStrategy` base (`app/engine/strategy/algorithms/_rsi_range_base.py`)
# rather than on `SpyStrategyCAlgorithm` itself, but the closure and its
# exclusions are otherwise identical in shape to `sma_crossover`'s: every
# excluded file below is reached only through
# `app/engine/strategy/base.py`/`app/engine/execution/*`'s own general,
# strategy-agnostic imports, never from `RsiRangeStrategy.evaluate_signal_bar`'s
# decision math.
_SPY_C_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting; evaluate_signal_bar() reads only the consolidated bar, never portfolio state, to compute its facts.',
    insight="Reached via strategy/base.py's StrategyContext.emit_insight() plumbing, which RsiRangeStrategy.commit_signal_decision never calls — and even where a program does call it, that only happens after _build_trace() has already produced the immutable EvaluationTrace.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by RsiRangeStrategy; not consulted by evaluate_signal_bar() either way.',
)

# Same triage, for `deployment_validation`'s own closure (issue #1730 Slice
# 5, last promotion). Its decision math never touches portfolio state or the
# Insight framework at all — evaluate_signal_bar reads only bar.open/
# bar.close and the calendar-derived session window, and
# commit_signal_decision calls ctx.set_holdings/ctx.liquidate directly
# (instrument_surface="explicit") rather than ctx.emit_signal_intent or
# ctx.emit_insight — but portfolio.py, insight.py, and insight_manager.py
# are still transitively reached through strategy/base.py's own
# general, strategy-agnostic imports (StrategyContext holds a Portfolio and
# exposes emit_insight()), the same way every other program's closure reaches
# them.
_DEPLOYMENT_VALIDATION_SIGNAL_DECISION_CLOSURE_EXCLUSIONS: dict[str, str] = _closure_exclusions(
    portfolio='Cash/holdings/fill accounting reached only through StrategyContext.set_holdings()/liquidate(), both called from commit_signal_decision() after _build_trace() has already produced the immutable EvaluationTrace; evaluate_signal_bar() reads only bar.open/bar.close, never portfolio state, to compute its facts.',
    insight="Reached only via strategy/base.py's StrategyContext.emit_insight() plumbing, which DeploymentValidationConsecutiveGreen never calls at all (no Insight is ever constructed) — general, strategy-agnostic import surface, not decision math this program touches.",
    insight_manager='Reached only via StrategyContext.emit_insight(), never called by DeploymentValidationConsecutiveGreen; not consulted by evaluate_signal_bar() either way.',
)


# One place the matrix test reads to find a program's triage, so a program
# added later is covered by the closure matrix the moment it appears here
# rather than needing its own near-identical test file.
_CLOSURE_EXCLUSIONS_BY_PROGRAM: dict[str, dict[str, str]] = {
    "ema_crossover_signal": _EMA_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "sma_crossover": _SMA_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "rsi_mean_reversion": _RSI_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "spy_strategy_a": _SPY_STRATEGY_A_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "spy_strategy_b": _SPY_STRATEGY_B_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "spy_strategy_c": _SPY_C_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
    "deployment_validation": _DEPLOYMENT_VALIDATION_SIGNAL_DECISION_CLOSURE_EXCLUSIONS,
}


def _imported_first_party_modules(node: ast.AST) -> list[str]:
    """Return every ``app.*`` module named by one AST import node."""
    if isinstance(node, ast.ImportFrom):
        if node.level == 0 and node.module and node.module.startswith("app"):
            return [node.module]
        return []
    if isinstance(node, ast.Import):
        return [alias.name for alias in node.names if alias.name.startswith("app")]
    return []


def _module_to_relative_path(module: str, *, service_root: Path) -> str | None:
    parts = module.split(".")
    candidate = Path(*parts).with_suffix(".py")
    if (service_root / candidate).is_file():
        return candidate.as_posix()
    candidate = Path(*parts, "__init__.py")
    if (service_root / candidate).is_file():
        return candidate.as_posix()
    return None


def signal_decision_import_closure(
    *,
    roots: Iterable[str],
    service_root: Path = _SERVICE_ROOT,
) -> set[str]:
    """Return the transitive first-party (``app.``) import closure of ``roots``.

    Walks the full AST — including deferred, function-local imports — so a
    closure member reached only inside a function (e.g. the
    ``app.lean_sidecar.trading_calendar`` import inside
    ``app/engine/live/indicator_state.py``) is still counted: a deferred
    import still executes, and its bytes still ship.
    """
    seen: set[str] = set()
    frontier = list(roots)
    while frontier:
        relative = frontier.pop()
        if relative in seen:
            continue
        seen.add(relative)
        source = (service_root / relative).read_text(encoding="utf-8")
        tree = ast.parse(source, filename=relative)
        for node in ast.walk(tree):
            for module in _imported_first_party_modules(node):
                member = _module_to_relative_path(module, service_root=service_root)
                if member is not None and member not in seen:
                    frontier.append(member)
    return seen


class QualificationFailedError(RuntimeError):
    """A program's golden-trace qualification suite did not pass."""


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="run_signal_program_build_qualification",
        description=(
            "Run each registered Signal Program's golden-trace qualification suite and, "
            "only on a pass, emit its build receipt into the committed manifest."
        ),
    )
    parser.add_argument("--manifest-path", type=Path, default=DEFAULT_QUALIFICATION_MANIFEST)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed manifest differs from a freshly qualified run.",
    )
    parser.add_argument(
        "--qualified-at-ms",
        type=int,
        default=None,
        help=(
            "Timestamp stamped on a brand-new receipt. Defaults to now. Ignored for any "
            "program whose qualified identity is unchanged from the committed manifest."
        ),
    )
    return parser.parse_args(argv)


def _run_qualification_suite(test_ref: str) -> None:
    """Run one pytest node id; raise with captured output on any non-zero exit."""
    command = [sys.executable, "-m", "pytest", "-q", test_ref]
    try:
        completed = subprocess.run(
            command,
            cwd=_SERVICE_ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=_PYTEST_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        raise QualificationFailedError(
            f"golden-trace qualification timed out after {_PYTEST_TIMEOUT_SECONDS}s: {test_ref}"
        ) from exc
    except OSError as exc:
        raise QualificationFailedError(f"could not execute pytest for {test_ref}: {exc}") from exc
    if completed.returncode != 0:
        raise QualificationFailedError(
            f"golden-trace qualification failed for {test_ref} (exit {completed.returncode}); "
            f"stdout tail: {completed.stdout[-2000:]}; stderr tail: {completed.stderr[-2000:]}"
        )


# The identity a receipt's timestamp is earned against. Changing any of these
# is what mints a fresh ``qualified_at_ms``; everything else about a receipt
# can be reshaped without re-dating it.
_QUALIFIED_IDENTITY_FIELDS = (
    "program_key",
    "program_version",
    "golden_trace_root",
    "artifact_digest",
    "qualification_suite",
)


def _prior_qualified_at_ms(path: Path) -> dict[tuple[str, ...], int]:
    """Map each already-qualified identity to the timestamp it earned.

    Reads the committed manifest as raw JSON rather than through
    ``ProgramBuildQualificationManifest``. The only thing wanted here is the
    prior timestamp for an unchanged identity, and parsing through the model
    would couple timestamp reuse to the *current* receipt schema — so a schema
    bump would re-date every receipt, which is exactly the churn the reuse
    rule exists to prevent (issue #1735 bumps it to v2). A receipt missing any
    identity field simply does not match, and mints a fresh timestamp.

    A corrupt manifest still raises: silently re-dating every receipt because
    the file could not be parsed is the failure this whole job exists to
    prevent.
    """
    if not path.is_file():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    index: dict[tuple[str, ...], int] = {}
    for receipt in payload.get("receipts", ()):
        identity = tuple(receipt.get(field) for field in _QUALIFIED_IDENTITY_FIELDS)
        stamp = receipt.get("qualified_at_ms")
        if any(part is None for part in identity) or not isinstance(stamp, int):
            continue
        index[identity] = stamp
    return index


def qualify_signal_program_builds(
    *,
    prior_qualified_at_ms: dict[tuple[str, ...], int],
    fresh_qualified_at_ms: int,
) -> dict[str, Any]:
    """Run every registered qualification suite and assemble the build-receipt manifest.

    Raises ``QualificationFailedError`` before returning anything if any
    program's suite fails — a behavior change without a matching
    program/root update is caught here, not silently admitted later at
    Start/Resume.
    """
    receipts: list[dict[str, Any]] = []
    for program_key in sorted(_QUALIFICATION_SUITES):
        registration = _STRATEGY_REGISTRY.get(program_key)
        contract = registration.signal_program_contract if registration is not None else None
        if registration is None or contract is None or registration.signal_program_factory is None:
            raise QualificationFailedError(
                f"{program_key} is listed in _QUALIFICATION_SUITES but is not a registered "
                "Signal Program (missing signal_program_contract or signal_program_factory)"
            )
        qualification_suite = _QUALIFICATION_SUITES[program_key]
        _run_qualification_suite(qualification_suite)
        identity = (
            program_key,
            contract.program_version,
            contract.golden_trace_root,
            running_artifact_digest(contract),
            qualification_suite,
        )
        qualified_at_ms = prior_qualified_at_ms.get(identity, fresh_qualified_at_ms)
        receipts.append(
            qualification_receipt_payload(
                program_key=program_key,
                contract=contract,
                qualified_at_ms=qualified_at_ms,
                qualification_suite=qualification_suite,
            )
        )
    return {"schema_version": 2, "receipts": receipts}


def _manifest_text(manifest: dict[str, Any]) -> str:
    """Round-trip through the shared schema, then format exactly like the committed file."""
    ProgramBuildQualificationManifest.model_validate(manifest)
    return json.dumps(manifest, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    prior_qualified_at_ms = _prior_qualified_at_ms(args.manifest_path)
    fresh_qualified_at_ms = (
        args.qualified_at_ms if args.qualified_at_ms is not None else now_ms_utc()
    )

    try:
        manifest = qualify_signal_program_builds(
            prior_qualified_at_ms=prior_qualified_at_ms,
            fresh_qualified_at_ms=fresh_qualified_at_ms,
        )
    except QualificationFailedError as exc:
        sys.stderr.write(f"{exc}\n")
        return 1

    text = _manifest_text(manifest)

    if args.check:
        current = args.manifest_path.read_text(encoding="utf-8") if args.manifest_path.is_file() else None
        if current == text:
            sys.stdout.write(f"{args.manifest_path} is up to date.\n")
            return 0
        sys.stderr.write(
            f"{args.manifest_path} is stale; regenerate with:\n"
            "  python -m scripts.run_signal_program_build_qualification\n"
        )
        return 1

    atomic_write_bytes(args.manifest_path, text.encode("utf-8"))
    sys.stdout.write(f"Wrote {len(manifest['receipts'])} build receipt(s) to {args.manifest_path}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
