import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { RouterLink } from "@angular/router";

import { KatexDirective } from "../../../shared/katex.directive";
import type { MetricVariant } from "./analytical-metric-catalog.models";

/** Presentational catalog entry; all definition data is generated by Python. */
@Component({
  selector: "app-metric-reference-entry",
  imports: [KatexDirective, RouterLink],
  templateUrl: "./metric-reference-entry.component.html",
  styleUrl: "./metric-reference-entry.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MetricReferenceEntryComponent {
  readonly variant = input.required<MetricVariant>();
  readonly alternative = input<MetricVariant | null>(null);
  readonly runId = input<number | null>(null);

  readonly compareQuery = computed(() => {
    const alternative = this.alternative();
    if (!alternative) return {};
    return {
      metric: alternative.metric_id,
      variant: alternative.variant_id,
      producer: alternative.producer,
      contract: alternative.contract_id ?? undefined,
      run: this.runId() ?? undefined,
    };
  });
}
