import { ChangeDetectionStrategy, Component, computed, input, model } from "@angular/core";
import { RouterLink } from "@angular/router";
import { TabsModule } from "primeng/tabs";

import { ReceiptLabelPipe } from "../../../shared/pipes/receipt-label.pipe";
import type { MetricVariant } from "./analytical-metric-catalog.models";
import { MetricCalculationContractComponent } from "./metric-calculation-contract.component";
import { MetricDeveloperReferenceComponent } from "./metric-developer-reference.component";
import { MetricTraderExplanationComponent } from "./metric-trader-explanation.component";

export type MetricManualTab = "explain" | "calculation" | "developer";

/** Presentational catalog entry; all definition data is generated by Python. */
@Component({
  selector: "app-metric-reference-entry",
  imports: [
    MetricCalculationContractComponent,
    MetricDeveloperReferenceComponent,
    MetricTraderExplanationComponent,
    ReceiptLabelPipe,
    RouterLink,
    TabsModule,
  ],
  templateUrl: "./metric-reference-entry.component.html",
  styleUrl: "./metric-reference-entry.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MetricReferenceEntryComponent {
  readonly variant = input.required<MetricVariant>();
  readonly alternative = input<MetricVariant | null>(null);
  readonly runId = input<number | null>(null);
  readonly activeTab = model<MetricManualTab>("explain");

  readonly compareQuery = computed(() => {
    const alternative = this.alternative();
    if (!alternative) return {};
    return {
      metric: alternative.metric_id,
      variant: alternative.variant_id,
      producer: alternative.producer,
      contract: alternative.contract_id ?? undefined,
      run: this.runId() ?? undefined,
    };
  });

  onTabChange(value: string | number | undefined): void {
    if (value === "explain" || value === "calculation" || value === "developer") {
      this.activeTab.set(value);
    }
  }
}
