"""Test 2 — QC ↔ Python native-feed shadowing (§ 8.2).

Operational-tolerance comparison of the QC Cloud algorithm output (run
on QC's native data feed) against Python's output (run on Polygon
historical), over the spec-defined evaluation window:

  evaluation [2025-08-01 00:00 ET, 2025-11-01 00:00 ET) RTH-only
  warmup     pre-roll from 2025-07-15

Per spec § 8.2: data-class divergences are informational; engine-class
divergences are blocking.

Tolerances per § 6.3 cross-feed shadowing:
  EMA atol = 0.10, RSI atol = 2.0
Strategy-level deltas tracked but not asserted by this test (the
operator signs off via PR comment after reviewing the day-by-day
classification).

Two prerequisites for this test to actually run:
  1. QC Cloud Test 2 export committed at
     ``references/qc-shadow/backtests/2025-08-01_to_2025-11-01/{trades,indicators}.csv``
  2. Python's matching backtest output committed at
     ``PythonDataService/app/engine/tests/fixtures/python_native_feed_2025-08-01_to_2025-11-01/{trades,indicators}.csv``

The Python fixture is generated by a separate operator workflow (see
``references/qc-shadow/README.md`` § "Operator workflow — Test 2"); it
involves running ``BacktestEngine`` against Polygon historical SPY data
and dumping per-bar indicators + trades. Generating it on every test
invocation would require Polygon API access and several minutes of
network IO — out of scope for a unit-test suite.

The test ``pytest.skip``s cleanly until both files appear, so it serves
as scaffolding now and as the real Test 2 gate later.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from app.engine.live.reconcile import (
    CrossEngineClass,
    CrossEngineTolerances,
    classify_cross_engine,
)

REPO_ROOT = Path(__file__).resolve().parents[4]
QC_DIR = REPO_ROOT / "references" / "qc-shadow" / "backtests" / "2025-08-01_to_2025-11-01"
QC_TRADES = QC_DIR / "trades.csv"
QC_INDICATORS = QC_DIR / "indicators.csv"

PYTHON_NATIVE_DIR = (
    REPO_ROOT
    / "PythonDataService"
    / "app"
    / "engine"
    / "tests"
    / "fixtures"
    / "python_native_feed_2025-08-01_to_2025-11-01"
)
PYTHON_TRADES = PYTHON_NATIVE_DIR / "trades.csv"
PYTHON_INDICATORS = PYTHON_NATIVE_DIR / "indicators.csv"

EVAL_START_MS = int(pd.Timestamp("2025-08-01 00:00", tz="America/New_York").timestamp() * 1000)
EVAL_END_MS = int(pd.Timestamp("2025-11-01 00:00", tz="America/New_York").timestamp() * 1000)

requires_exports = pytest.mark.skipif(
    not (
        QC_TRADES.exists()
        and QC_INDICATORS.exists()
        and PYTHON_TRADES.exists()
        and PYTHON_INDICATORS.exists()
    ),
    reason=(
        "Test 2 prerequisites missing. Need (a) QC Cloud Test 2 export at "
        f"{QC_DIR.relative_to(REPO_ROOT)} and (b) Python native-feed fixture at "
        f"{PYTHON_NATIVE_DIR.relative_to(REPO_ROOT)}. "
        "See references/qc-shadow/README.md → 'Operator workflow — Test 2'."
    ),
)


def _load_eval_window(path: Path) -> pd.DataFrame:
    """Load CSV and drop pre-roll rows so the comparison is over the half-open eval window."""
    df = pd.read_csv(path)
    if "bar_close_ms" in df.columns:
        ts_col = "bar_close_ms"
    elif "entry_time_ms" in df.columns:
        ts_col = "entry_time_ms"
    else:
        raise ValueError(f"{path} has no recognized timestamp column")
    return df[(df[ts_col] >= EVAL_START_MS) & (df[ts_col] < EVAL_END_MS)].reset_index(drop=True)


@requires_exports
def test_zero_engine_class_divergences_in_eval_window() -> None:
    """Engine-class divergence count must be zero — § 8.2 hard gate.

    A single engine-class row blocks paper week. Data-class
    divergences are reported (printed to test output) but not asserted —
    operator sign-off path.
    """
    qc_ind = _load_eval_window(QC_INDICATORS)
    py_ind = _load_eval_window(PYTHON_INDICATORS)
    merged = qc_ind.merge(py_ind, on="bar_close_ms", how="inner", suffixes=("_qc", "_py"))

    tols = CrossEngineTolerances()
    counts = {cls: 0 for cls in CrossEngineClass}
    engine_rows: list[dict] = []
    for _, row in merged.iterrows():
        cls = classify_cross_engine(
            py_ema5=float(row["ema5_py"]),
            py_ema10=float(row["ema10_py"]),
            py_rsi=float(row["rsi_py"]),
            py_signal=str(row["signal_py"]),
            qc_ema5=float(row["ema5_qc"]),
            qc_ema10=float(row["ema10_qc"]),
            qc_rsi=float(row["rsi_qc"]),
            qc_signal=str(row["signal_qc"]),
            tols=tols,
        )
        counts[cls] += 1
        if cls == CrossEngineClass.ENGINE:
            engine_rows.append(
                {
                    "bar_close_ms": int(row["bar_close_ms"]),
                    "py_signal": row["signal_py"],
                    "qc_signal": row["signal_qc"],
                    "py_ema5": row["ema5_py"],
                    "qc_ema5": row["ema5_qc"],
                }
            )

    print(
        f"\nTest 2 cross-engine classification — bars={len(merged)} "
        f"none={counts[CrossEngineClass.NONE]} "
        f"data={counts[CrossEngineClass.DATA]} "
        f"engine={counts[CrossEngineClass.ENGINE]}"
    )

    assert counts[CrossEngineClass.ENGINE] == 0, (
        f"§ 8.2 hard gate: {counts[CrossEngineClass.ENGINE]} engine-class divergence(s). "
        f"First 3: {engine_rows[:3]}"
    )


@requires_exports
def test_trade_count_within_strategy_level_tolerance() -> None:
    """Strategy-level smoke check on trade count.

    The full strategy-level tolerance set (§ 6.3) is exercised by the
    daily ``reconcile.py`` runs during paper week — here we only assert
    the coarsest invariant: trade counts must be in the same ballpark
    after dropping pre-roll trades. Asserts |Δ| ≤ 2 absolute.
    """
    qc_trades = _load_eval_window(QC_TRADES)
    py_trades = _load_eval_window(PYTHON_TRADES)
    delta = abs(len(qc_trades) - len(py_trades))
    assert delta <= 2, (
        f"trade-count delta {delta} exceeds ±2 envelope: "
        f"qc={len(qc_trades)} py={len(py_trades)}"
    )
