using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations
{
    /// <summary>
    /// Ownership of the Recency Chart tables ("RecencyLaunches", "RecencyRuns",
    /// "RecencyTrades", "RecencyTradeMemberships") moves to the Python service
    /// (PRD #1927, ADR 0057). The entities leave this model, so the model differ
    /// scaffolded four <c>DropTable</c> operations here; they are deliberately
    /// removed. The tables and every row in them stay exactly as they are — the
    /// Python service's <c>research/persistence/schema.py</c> (version 3) now
    /// declares them with <c>CREATE TABLE IF NOT EXISTS</c> and is their only
    /// writer. The model snapshot was regenerated by the tool, not edited, so a
    /// later migration sees no Recency tables to drop either.
    ///
    /// <c>Down</c> is likewise a no-op: the tables were never dropped, so there
    /// is nothing to recreate, and recreating them over live data would fail.
    /// </summary>
    public partial class TransferRecencyTablesToPython : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty: see the class summary.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty: see the class summary.
        }
    }
}
