// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.DataLab.DataLabSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Adjusted")
                        .HasColumnType("boolean");

                    b.Property<string>("ChartSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntriesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("ForwardFill")
                        .HasColumnType("boolean");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("DataLabSessions");
                });

            modelBuilder.Entity("Backend.Models.MarketData.BacktestTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CumulativePnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("EntryTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("ExitTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSyntheticExit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("SignalReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StrategyExecutionId")
                        .HasColumnType("integer");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyExecutionId");

                    b.ToTable("BacktestTrades");
                });

            modelBuilder.Entity("Backend.Models.MarketData.DataLakeArtifact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long?>("CompletedAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("CorpActionRevision")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("DataContractHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("DataType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("FetchedAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("FirstBarStartMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastBarStartMs")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<long?>("LeaseExpiresAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Market")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PriceAdjustmentMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderParams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("TradingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Market", "Symbol", "Resolution", "DataType", "TradingDate");

                    b.ToTable("DataLakeArtifacts");
                });

            modelBuilder.Entity("Backend.Models.MarketData.DataLakeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CompletedAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("DataAvailabilityHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("EngineRunId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EngineStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EnsureDataResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("EnsureDataStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ManifestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("RequestedAtMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RunSpec")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("StartedAtMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("StrategyExecutionId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StrategyExecutionId");

                    b.ToTable("DataLakeRuns");
                });

            modelBuilder.Entity("Backend.Models.MarketData.OptionsIvSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DteHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("DteLow")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Iv30dAtm")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("Iv30dCall")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("Iv30dPut")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("PriceSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("StockClose")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TradingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "TradingDate")
                        .IsUnique();

                    b.ToTable("OptionsIvSnapshots");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ParityVerdict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeftExecutionId")
                        .HasColumnType("integer");

                    b.Property<string>("ParityGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RightExecutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("VerdictJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("VerdictVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeftExecutionId", "RightExecutionId")
                        .IsUnique();

                    b.HasIndex("ParityGroupId");

                    b.HasIndex("RightExecutionId");

                    b.ToTable("ParityVerdicts");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Quote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AskExchange")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AskPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("AskSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<long?>("BidExchange")
                        .HasColumnType("bigint");

                    b.Property<decimal>("BidPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("BidSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "Timestamp");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ReferenceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeclarationDate")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("SplitFrom")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("SplitTo")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "DataType", "EventDate");

                    b.ToTable("ReferenceData");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ResearchExperiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdfPValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("BarsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ICPValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("ICTStat")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<bool>("IsMonotonic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStationary")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KpssPValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MeanIC")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MonotonicityRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<bool>("PassedValidation")
                        .HasColumnType("boolean");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "FeatureName", "CreatedAt");

                    b.ToTable("ResearchExperiments");
                });

            modelBuilder.Entity("Backend.Models.MarketData.SignalExperiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarsUsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestCostBps")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("BestThreshold")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FlipSign")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MeanOosSharpe")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("OverallGrade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("OverallPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("RegimeGateEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "FeatureName", "CreatedAt");

                    b.ToTable("SignalExperiments");
                });

            modelBuilder.Entity("Backend.Models.MarketData.StockAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("Timespan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TransactionCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("VolumeWeightedAveragePrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TickerId", "Timestamp", "Timespan");

                    b.ToTable("StockAggregates");
                });

            modelBuilder.Entity("Backend.Models.MarketData.StrategyExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alpha")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("AnnualStandardDeviation")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Beta")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("BrokeragePolicy")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<decimal?>("CommissionPerOrder")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("CompoundingAnnualReturn")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("DataPolicyJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("DrawdownRecoveryDays")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EquityCurveJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FillMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("FinalEquity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("InsightSummaryJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("InformationRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("InitialCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("LeanRunId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeanStatisticsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParityGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("ProbabilisticSharpeRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("ProfitFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("RunVerdictJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("SharpeRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("SortinoRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("Timespan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalFees")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalPnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrackingError")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("TreynorRatio")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ValidationAnalyticsJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("ValueAtRisk95")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("ValueAtRisk99")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("VerdictGrade")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("VerdictSignal")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("VerdictVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("Source");

                    b.HasIndex("ParityGroupId");

                    b.HasIndex("Source", "LeanRunId")
                        .IsUnique()
                        .HasFilter("\"LeanRunId\" IS NOT NULL");

                    b.HasIndex("TickerId", "StrategyName");

                    b.ToTable("StrategyExecutions");
                });

            modelBuilder.Entity("Backend.Models.MarketData.TechnicalIndicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Histogram")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Signal")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("Timespan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("ValuesJson")
                        .HasColumnType("text");

                    b.Property<int>("Window")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "IndicatorType", "Timestamp");

                    b.ToTable("TechnicalIndicators");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryExchange")
                        .HasColumnType("text");

                    b.Property<string>("SanitizationSummary")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "Market")
                        .IsUnique();

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Exchange")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Size")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TickerId", "Timestamp");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialCash")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.OptionContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Strike")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UnderlyingTickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UnderlyingTickerId", "Strike", "Expiration", "OptionType");

                    b.ToTable("OptionContracts");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.OptionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EntryDelta")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("EntryGamma")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("EntryIV")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("EntryTheta")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("EntryVega")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("OptionContractId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OptionContractId");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.ToTable("OptionLegs");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid?>("OptionContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionContractId");

                    b.HasIndex("TickerId");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Equity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MarginUsed")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MarketValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("RealizedPnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UnrealizedPnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Timestamp");

                    b.ToTable("PortfolioSnapshots");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PortfolioTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ExecutionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OptionContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionContractId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TickerId");

                    b.HasIndex("AccountId", "ExecutionTimestamp");

                    b.ToTable("PortfolioTrades");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("AvgCostBasis")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NetQuantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OptionContractId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RealizedPnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionContractId");

                    b.HasIndex("TickerId");

                    b.HasIndex("AccountId", "TickerId", "Status");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PositionLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("RealizedPnL")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.HasIndex("PositionId", "OpenedAt");

                    b.ToTable("PositionLots");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.RiskRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Enabled");

                    b.ToTable("RiskRules");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.StrategyAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapitalAllocated")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StrategyExecutionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrategyExecutionId");

                    b.HasIndex("AccountId", "StrategyExecutionId");

                    b.ToTable("StrategyAllocations");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.StrategyTradeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("StrategyExecutionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyExecutionId");

                    b.HasIndex("TradeId");

                    b.ToTable("StrategyTradeLinks");
                });

            modelBuilder.Entity("Backend.Models.MarketData.BacktestTrade", b =>
                {
                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "StrategyExecution")
                        .WithMany("Trades")
                        .HasForeignKey("StrategyExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyExecution");
                });

            modelBuilder.Entity("Backend.Models.MarketData.DataLakeRun", b =>
                {
                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "StrategyExecution")
                        .WithMany()
                        .HasForeignKey("StrategyExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StrategyExecution");
                });

            modelBuilder.Entity("Backend.Models.MarketData.OptionsIvSnapshot", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ParityVerdict", b =>
                {
                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "LeftExecution")
                        .WithMany()
                        .HasForeignKey("LeftExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "RightExecution")
                        .WithMany()
                        .HasForeignKey("RightExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeftExecution");

                    b.Navigation("RightExecution");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Quote", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany("Quotes")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ReferenceData", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.ResearchExperiment", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.SignalExperiment", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.StockAggregate", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany("Aggregates")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.StrategyExecution", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.TechnicalIndicator", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany("Indicators")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Trade", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany("Trades")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.OptionContract", b =>
                {
                    b.HasOne("Backend.Models.MarketData.Ticker", "UnderlyingTicker")
                        .WithMany()
                        .HasForeignKey("UnderlyingTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnderlyingTicker");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.OptionLeg", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.OptionContract", "OptionContract")
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.PortfolioTrade", "Trade")
                        .WithOne("OptionLeg")
                        .HasForeignKey("Backend.Models.Portfolio.OptionLeg", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionContract");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Order", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.OptionContract", "OptionContract")
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("OptionContract");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PortfolioSnapshot", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PortfolioTrade", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany("Trades")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.OptionContract", "OptionContract")
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Portfolio.Order", "Order")
                        .WithMany("Trades")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("OptionContract");

                    b.Navigation("Order");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Position", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany("Positions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.OptionContract", "OptionContract")
                        .WithMany()
                        .HasForeignKey("OptionContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.MarketData.Ticker", "Ticker")
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("OptionContract");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PositionLot", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Position", "Position")
                        .WithMany("Lots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.PortfolioTrade", "Trade")
                        .WithMany("Lots")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.RiskRule", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.StrategyAllocation", b =>
                {
                    b.HasOne("Backend.Models.Portfolio.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "StrategyExecution")
                        .WithMany()
                        .HasForeignKey("StrategyExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("StrategyExecution");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.StrategyTradeLink", b =>
                {
                    b.HasOne("Backend.Models.MarketData.StrategyExecution", "StrategyExecution")
                        .WithMany()
                        .HasForeignKey("StrategyExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Portfolio.PortfolioTrade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyExecution");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Backend.Models.MarketData.StrategyExecution", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Backend.Models.MarketData.Ticker", b =>
                {
                    b.Navigation("Aggregates");

                    b.Navigation("Indicators");

                    b.Navigation("Quotes");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Account", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Positions");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Order", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.PortfolioTrade", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("OptionLeg");
                });

            modelBuilder.Entity("Backend.Models.Portfolio.Position", b =>
                {
                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
