import type {
  BotLifecycleChartView,
  LifecycleChartNode,
} from '../api/live-instances.types';
export { makeOperatorSurfaceFixture } from './operator-surface-fixtures';

const EMPTY_NODE_EVIDENCE: Pick<LifecycleChartNode, 'ts_ms' | 'ts_ms_resolved' | 'receipts'> = {
  ts_ms: null,
  ts_ms_resolved: false,
  receipts: [],
};

export function makeLifecycleChartFixture(
  overrides: Partial<BotLifecycleChartView> = {},
): BotLifecycleChartView {
  const chart: BotLifecycleChartView = {
    chart_id: 'bot_lifecycle_v1',
    selected_bot_id: 'sid-x',
    title: 'Bot lifecycle overview',
    global_graph: {
      graph_id: 'global',
      title: 'Bot lifecycle overview',
      primary_node_id: 'deploy',
      nodes: [
        {
          id: 'deploy',
          label: 'Deploy or start',
          technical_label: 'Host process',
          lane: 'bot',
          status: 'active',
          status_label: 'Here now',
          expandable: true,
          subgraph_id: 'deploy',
          evidence_summary: 'Backend start gate is ready.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'preflight',
          label: 'Pre-flight gates',
          technical_label: 'Config and readiness',
          lane: 'bot',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'preflight',
          evidence_summary: 'Readiness is unknown.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'account_safety',
          label: 'Account safety',
          technical_label: 'Freeze, safety, connection',
          lane: 'account',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'account_safety',
          evidence_summary: 'Broker evidence is unavailable.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'reconcile',
          label: 'Reconcile broker state',
          technical_label: 'Cold-start receipt',
          lane: 'broker',
          status: 'blocked',
          status_label: 'Blocked',
          expandable: true,
          subgraph_id: 'reconcile',
          evidence_summary: 'Reconciliation is blocked.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'activate',
          label: 'Activate bot',
          technical_label: 'Durable desired state',
          lane: 'bot',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'activate',
          evidence_summary: 'Desired state is unknown.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'active',
          label: 'Monitor live bot',
          technical_label: 'Running loop',
          lane: 'bot',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: false,
          subgraph_id: null,
          evidence_summary: 'Bot is not active.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'submit_order',
          label: 'Submit order path',
          technical_label: 'Signal -> WAL -> order',
          lane: 'broker',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'submit_order',
          evidence_summary: 'Order path is waiting.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'broker_writer',
          label: 'Broker activity',
          technical_label: 'Publisher health',
          lane: 'broker',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'broker_writer',
          evidence_summary: 'Broker-activity publisher health is unavailable.',
          ...EMPTY_NODE_EVIDENCE,
        },
        {
          id: 'recovery',
          label: 'Recovery lane',
          technical_label: 'Flatten, halt, redeploy',
          lane: 'recovery',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'recovery',
          evidence_summary: 'Recovery is waiting.',
          ...EMPTY_NODE_EVIDENCE,
        },
      ],
      edges: [],
    },
    subgraphs: {
      deploy: {
        graph_id: 'deploy',
        title: 'Deploy and start internals',
        primary_node_id: 'host_state',
        nodes: [
          {
            id: 'host_state',
            label: 'Host state',
            technical_label: 'IDLE',
            lane: 'bot',
            status: 'active',
            status_label: 'Here now',
            expandable: false,
            subgraph_id: null,
            evidence_summary: 'Daemon is reachable.',
            ...EMPTY_NODE_EVIDENCE,
          },
        ],
        edges: [],
      },
    },
    actions: [
      {
        id: 'start_process',
        label: 'Start bot process',
        enabled: true,
        reason_code: null,
        reason_headline: 'Available',
        reason_detail: 'Backend-authored start request is ready.',
        target_node_id: 'deploy',
        tone: 'primary',
      },
    ],
  };
  return { ...chart, ...overrides };
}
