import type { BotLifecycleChartView } from '../api/live-instances.types';

export function makeLifecycleChartFixture(
  overrides: Partial<BotLifecycleChartView> = {},
): BotLifecycleChartView {
  const chart: BotLifecycleChartView = {
    chart_id: 'bot_lifecycle_v1',
    selected_bot_id: 'sid-x',
    title: 'Bot lifecycle overview',
    global_graph: {
      graph_id: 'global',
      title: 'Bot lifecycle overview',
      primary_node_id: 'deploy',
      nodes: [
        {
          id: 'deploy',
          label: 'Deploy or start',
          technical_label: 'Host process',
          lane: 'bot',
          status: 'active',
          expandable: true,
          subgraph_id: 'deploy',
          evidence_summary: 'Backend start gate is ready.',
        },
        {
          id: 'preflight',
          label: 'Pre-flight gates',
          technical_label: 'Config and readiness',
          lane: 'bot',
          status: 'unknown',
          expandable: true,
          subgraph_id: 'preflight',
          evidence_summary: 'Readiness is unknown.',
        },
        {
          id: 'account_safety',
          label: 'Account safety',
          technical_label: 'Freeze, safety, connection',
          lane: 'account',
          status: 'unknown',
          expandable: true,
          subgraph_id: 'account_safety',
          evidence_summary: 'Broker evidence is unavailable.',
        },
        {
          id: 'reconcile',
          label: 'Reconcile broker state',
          technical_label: 'Cold-start receipt',
          lane: 'broker',
          status: 'blocked',
          expandable: true,
          subgraph_id: 'reconcile',
          evidence_summary: 'Reconciliation is blocked.',
        },
        {
          id: 'activate',
          label: 'Activate bot',
          technical_label: 'Durable desired state',
          lane: 'bot',
          status: 'unknown',
          expandable: true,
          subgraph_id: 'activate',
          evidence_summary: 'Desired state is unknown.',
        },
        {
          id: 'active',
          label: 'Monitor live bot',
          technical_label: 'Running loop',
          lane: 'bot',
          status: 'inactive',
          expandable: false,
          subgraph_id: null,
          evidence_summary: 'Bot is not active.',
        },
        {
          id: 'submit_order',
          label: 'Submit order path',
          technical_label: 'Signal -> WAL -> order',
          lane: 'broker',
          status: 'inactive',
          expandable: true,
          subgraph_id: 'submit_order',
          evidence_summary: 'Order path is waiting.',
        },
        {
          id: 'broker_writer',
          label: 'Broker writer',
          technical_label: 'placeOrder boundary',
          lane: 'broker',
          status: 'inactive',
          expandable: true,
          subgraph_id: 'broker_writer',
          evidence_summary: 'Broker writer is waiting.',
        },
        {
          id: 'recovery',
          label: 'Recovery lane',
          technical_label: 'Flatten, halt, redeploy',
          lane: 'recovery',
          status: 'inactive',
          expandable: true,
          subgraph_id: 'recovery',
          evidence_summary: 'Recovery is waiting.',
        },
      ],
      edges: [],
    },
    subgraphs: {
      deploy: {
        graph_id: 'deploy',
        title: 'Deploy and start internals',
        primary_node_id: 'host_state',
        nodes: [
          {
            id: 'host_state',
            label: 'Host state',
            technical_label: 'IDLE',
            lane: 'bot',
            status: 'active',
            expandable: false,
            subgraph_id: null,
            evidence_summary: 'Daemon is reachable.',
          },
        ],
        edges: [],
      },
    },
    actions: [
      {
        id: 'start_process',
        label: 'Start bot process',
        enabled: true,
        reason: 'Backend-authored start request is ready.',
        target_node_id: 'deploy',
        tone: 'primary',
      },
    ],
  };
  return { ...chart, ...overrides };
}
