import type { BotLifecycleChartView, OperatorSurface } from '../api/live-instances.types';

export function makeOperatorSurfaceFixture(
  overrides: Partial<OperatorSurface> = {},
): OperatorSurface {
  const surface: OperatorSurface = {
    schema_version: 1,
    host_process: {
      state: 'RUNNING',
      notice: null,
      copyable_command: null,
      start_capability: {
        enabled: false,
        run_id: null,
        request: null,
        disabled_reason_code: 'ALREADY_RUNNING',
        gate_results: [],
      },
    },
    prior_run: { classification: 'UNKNOWN' },
    broker: { safety_verdict: 'PAPER_ONLY', connection: 'CONNECTED' },
    configuration: { verdict: 'READY', reason_codes: [] },
    current_risk: {
      posture: 'FLAT',
      pending_order_count: 0,
      verdict: 'READY',
      unrealized_pnl: 0,
    },
    daily_order_cap: { used: 0, limit: 50_000 },
    action_plan: { consumption: 'ACTIVE', anomaly_verdict: 'READY' },
    account_owner: {
      account_id: 'DU123',
      generation: 4,
      phase: 'accepting',
      recorded_at_ms: 1_800_000_000_000,
      source: 'account_owner',
    },
    submit_readiness: {
      code: 'safe_to_submit',
      label: 'Safe to submit',
      explanation: 'Broker safety, submit capability, AccountOwner generation, reconciliation, and runtime proofs are all satisfied.',
      can_submit: true,
      blocking_reason_codes: [],
      template_id: 'operator_surface.submit_readiness.safe_to_submit',
      template_version: 1,
    },
    trader_guidance: {
      situation_code: 'ready_to_submit',
      headline: 'This bot is ready to submit paper orders.',
      explanation: 'All backend submit-readiness proofs are currently satisfied.',
      risk_headline: 'Submission gates are satisfied',
      risk_explanation: 'The surface is allowed to say safe to submit because the broker, submit lane, owner generation, and reconciliation proofs are all present.',
      primary_remediation: { kind: 'none', reason: 'READY' },
      additional_attention_groups: [],
      advanced_evidence: [
        {
          label: 'account_owner.generation',
          value: '4',
          source: 'account_owner',
          gate_id: null,
          ts_ms: 1_800_000_000_000,
          ts_ms_resolved: true,
        },
      ],
      template_id: 'operator_surface.trader_guidance.ready_to_submit',
      template_version: 1,
    },
    actions: {
      resume: {
        enabled: true,
        effect: 'LIVE_ACTUATION',
        disabled_reason_code: null,
        disabled_reasons: [],
        gate_results: [],
      },
      pause: {
        enabled: true,
        effect: 'LIVE_ACTUATION',
        disabled_reason_code: null,
        disabled_reasons: [],
        gate_results: [],
      },
      stop: {
        enabled: true,
        effect: 'DURABLE_ONLY',
        disabled_reason_code: null,
        disabled_reasons: [],
        gate_results: [],
      },
      flatten_and_pause: {
        enabled: false,
        effect: 'LIVE_ACTUATION',
        disabled_reason_code: 'NO_OWNED_POSITIONS',
        disabled_reasons: ['NO_OWNED_POSITIONS'],
        gate_results: [],
      },
      mark_poisoned: {
        enabled: true,
        effect: 'LIVE_ACTUATION',
        disabled_reason_code: null,
        disabled_reasons: [],
        gate_results: [],
      },
    },
    trading_session: {
      phase: 'RTH',
      permits_strategy_activity: true,
      next_transition_ms: null,
      timezone: 'America/New_York',
      as_of_ms: 1_800_000_000_000,
    },
    readiness_gates: [],
    runtime_freshness: null,
    control_plane: null,
    broker_observation_consistency: null,
    reconciliation: {
      state: 'CLEAN',
      failure_reason: null,
      adopted_intent_ids: [],
      last_reconcile_ms: 1_800_000_000_000,
    },
    broker_activity_health: null,
    incident_headline: null,
  };
  return { ...surface, ...overrides };
}

export function makeLifecycleChartFixture(
  overrides: Partial<BotLifecycleChartView> = {},
): BotLifecycleChartView {
  const chart: BotLifecycleChartView = {
    chart_id: 'bot_lifecycle_v1',
    selected_bot_id: 'sid-x',
    title: 'Bot lifecycle overview',
    global_graph: {
      graph_id: 'global',
      title: 'Bot lifecycle overview',
      primary_node_id: 'deploy',
      nodes: [
        {
          id: 'deploy',
          label: 'Deploy or start',
          technical_label: 'Host process',
          lane: 'bot',
          status: 'active',
          status_label: 'Here now',
          expandable: true,
          subgraph_id: 'deploy',
          evidence_summary: 'Backend start gate is ready.',
        },
        {
          id: 'preflight',
          label: 'Pre-flight gates',
          technical_label: 'Config and readiness',
          lane: 'bot',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'preflight',
          evidence_summary: 'Readiness is unknown.',
        },
        {
          id: 'account_safety',
          label: 'Account safety',
          technical_label: 'Freeze, safety, connection',
          lane: 'account',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'account_safety',
          evidence_summary: 'Broker evidence is unavailable.',
        },
        {
          id: 'reconcile',
          label: 'Reconcile broker state',
          technical_label: 'Cold-start receipt',
          lane: 'broker',
          status: 'blocked',
          status_label: 'Blocked',
          expandable: true,
          subgraph_id: 'reconcile',
          evidence_summary: 'Reconciliation is blocked.',
        },
        {
          id: 'activate',
          label: 'Activate bot',
          technical_label: 'Durable desired state',
          lane: 'bot',
          status: 'unknown',
          status_label: 'Unknown',
          expandable: true,
          subgraph_id: 'activate',
          evidence_summary: 'Desired state is unknown.',
        },
        {
          id: 'active',
          label: 'Monitor live bot',
          technical_label: 'Running loop',
          lane: 'bot',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: false,
          subgraph_id: null,
          evidence_summary: 'Bot is not active.',
        },
        {
          id: 'submit_order',
          label: 'Submit order path',
          technical_label: 'Signal -> WAL -> order',
          lane: 'broker',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'submit_order',
          evidence_summary: 'Order path is waiting.',
        },
        {
          id: 'broker_writer',
          label: 'Broker writer',
          technical_label: 'placeOrder boundary',
          lane: 'broker',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'broker_writer',
          evidence_summary: 'Broker writer is waiting.',
        },
        {
          id: 'recovery',
          label: 'Recovery lane',
          technical_label: 'Flatten, halt, redeploy',
          lane: 'recovery',
          status: 'inactive',
          status_label: 'Waiting',
          expandable: true,
          subgraph_id: 'recovery',
          evidence_summary: 'Recovery is waiting.',
        },
      ],
      edges: [],
    },
    subgraphs: {
      deploy: {
        graph_id: 'deploy',
        title: 'Deploy and start internals',
        primary_node_id: 'host_state',
        nodes: [
          {
            id: 'host_state',
            label: 'Host state',
            technical_label: 'IDLE',
            lane: 'bot',
            status: 'active',
            status_label: 'Here now',
            expandable: false,
            subgraph_id: null,
            evidence_summary: 'Daemon is reachable.',
          },
        ],
        edges: [],
      },
    },
    actions: [
      {
        id: 'start_process',
        label: 'Start bot process',
        enabled: true,
        reason: 'Backend-authored start request is ready.',
        target_node_id: 'deploy',
        tone: 'primary',
      },
    ],
  };
  return { ...chart, ...overrides };
}
