import { Component, ChangeDetectionStrategy, ElementRef, inject, viewChildren, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Accordion, AccordionContent, AccordionHeader, AccordionPanel } from 'primeng/accordion';
import { KatexDirective } from '../../../shared/katex.directive';

interface IndicatorDoc {
  name: string;
  displayName: string;
  formulaLatex: string;
  description: string;
  library: string;
  outputColumns: string[];
  defaultParams: string;
  interpretation: string[];
  recommendedTimeframes: string;
  dataNotes: string[];
  relatedIndicators: string[];
  panelType: 'overlay' | 'sub-panel';
  quickWhy: string;
  quickAnalogy: string;
  quickImpact: string;
  checkQuestion?: string;
  checkAnswer?: string;
  professionalRef: string;
  timeframeBehavior: string;
}

@Component({
  selector: 'app-data-lab-docs',
  standalone: true,
  imports: [CommonModule, RouterModule, Accordion, AccordionContent, AccordionHeader, AccordionPanel, KatexDirective],
  templateUrl: './data-lab-docs.component.html',
  styleUrls: ['./data-lab-docs.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DataLabDocsComponent {
  private el = inject(ElementRef);

  allIndicators: IndicatorDoc[] = [
    // ═══════════════════════════════════════════════════════════
    //  OVERLAY INDICATORS
    // ═══════════════════════════════════════════════════════════
    {
      name: 'ema',
      displayName: 'Exponential Moving Average (EMA)',
      formulaLatex: '\\text{EMA}_t = \\alpha \\cdot C_t + (1 - \\alpha) \\cdot \\text{EMA}_{t-1}, \\quad \\alpha = \\frac{2}{n + 1}',
      description: 'Gives more weight to recent prices. Default setup calculates 8 EMAs (5, 10, 20, 30, 40, 50, 100, 200) for multi-timeframe analysis. Each EMA instance adds one column.',
      library: 'pandas-ta (ta.ema)',
      outputColumns: ['ema_{length}'],
      defaultParams: 'length = 5, 10, 20, 30, 40, 50, 100, 200',
      interpretation: [
        'Price above EMA → bullish bias',
        'Price below EMA → bearish bias',
        'EMA crossovers (fast vs slow) generate trend signals',
        'Multiple EMAs form a "ribbon" — fanning = strong trend, converging = consolidation',
      ],
      recommendedTimeframes: '1m–1D+ (all timeframes)',
      dataNotes: [
        'Requires `length` warmup bars before producing valid values',
        'Sensitive to missing candles — EMA drifts if gaps exist',
      ],
      relatedIndicators: ['sma', 'dema', 'tema'],
      panelType: 'overlay',
      quickWhy: 'Find the "current heartbeat" of a stock. Reacts faster to recent news than a standard average.',
      quickAnalogy: 'Driving a car and looking mostly at the 50 feet behind you — it tells you about the turn you just made, not the road from five miles ago.',
      quickImpact: 'Spots trend changes early. If price stays above this line, the trend\'s "pulse" is healthy.',
      checkQuestion: 'If a stock suddenly crashes today, which line will drop faster: the SMA or the EMA?',
      checkAnswer: 'The EMA',
      professionalRef: 'Robert Goodell Brown (1956) and P.N. Haurlan (1960s)',
      timeframeBehavior: 'Hyper-sensitive on 1m/5m charts. Due to the 15-minute delay, a "cross" on the 1m chart represents a move that finished 15 minutes ago. Most reliable on Daily/Weekly charts.',
    },
    {
      name: 'sma',
      displayName: 'Simple Moving Average (SMA)',
      formulaLatex: '\\text{SMA}_t(n)=\\frac{1}{n}\\sum_{i=0}^{n-1}C_{t-i}',
      description: 'The arithmetic mean of the last n closing prices. One of the most widely used trend filters.',
      library: 'pandas-ta (ta.sma)',
      outputColumns: ['sma_{length}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Price above SMA → bullish bias',
        'Price below SMA → bearish bias',
        'SMA slope indicates trend strength',
        'SMA crossovers (fast vs slow) generate trend signals',
      ],
      recommendedTimeframes: '1h–1D+ (excellent long-term trend filter)',
      dataNotes: [
        'Requires `length` warmup bars',
        'Sensitive to missing candles / gaps',
      ],
      relatedIndicators: ['ema', 'wma', 'dema'],
      panelType: 'overlay',
      quickWhy: 'Find the "big picture" average. Treats every day in its window with equal importance.',
      quickAnalogy: 'The average temperature of a city. One heatwave doesn\'t change the climate. SMA shows you the "climate" of the stock.',
      quickImpact: 'Acts as a major floor or ceiling that big banks and institutions watch closely.',
      checkQuestion: 'For a one-year trend, would you use a 5-day SMA or a 200-day SMA?',
      checkAnswer: '200-day SMA',
      professionalRef: 'Richard Donchian (1930s) and John J. Murphy',
      timeframeBehavior: 'Inherently lagging. 15-minute delay is irrelevant for the 200-day SMA but makes the 5-period SMA useless for real-time scalping.',
    },
    {
      name: 'dema',
      displayName: 'Double Exponential Moving Average (DEMA)',
      formulaLatex: '\\text{DEMA}=2\\cdot EMA(n)-EMA(EMA(n))',
      description: 'Reduces lag compared to EMA by subtracting a smoothed EMA of EMA.',
      library: 'pandas-ta (ta.dema)',
      outputColumns: ['dema_{length}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Same usage as EMA (trend following)',
        'More responsive than SMA/EMA',
        'Helps reduce late entries in trends',
      ],
      recommendedTimeframes: '5m–1D (excellent on 4h–1D)',
      dataNotes: [
        'Warmup is larger than EMA due to nested smoothing',
      ],
      relatedIndicators: ['ema', 'tema', 'zlma'],
      panelType: 'overlay',
      quickWhy: 'For speed. Removes the "lag" that makes other averages feel slow and outdated.',
      quickAnalogy: 'If a standard average is a heavy bus, DEMA is a motorcycle that whips around corners instantly.',
      quickImpact: 'Entry and exit signals arrive much earlier than with traditional moving averages.',
      checkQuestion: 'Why would a trader use DEMA instead of SMA?',
      checkAnswer: 'To catch reversals faster',
      professionalRef: 'Patrick Mulloy (1994)',
      timeframeBehavior: 'High responsiveness but prone to "false starts" on 1m/5m charts because of the 15-minute feed delay.',
    },
    {
      name: 'tema',
      displayName: 'Triple Exponential Moving Average (TEMA)',
      formulaLatex: '\\text{TEMA}=3\\cdot EMA(n)-3\\cdot EMA(EMA(n))+EMA(EMA(EMA(n)))',
      description: 'Further reduces lag compared to DEMA while still smoothing price.',
      library: 'pandas-ta (ta.tema)',
      outputColumns: ['tema_{length}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Trend-following moving average',
        'Better for catching early reversals',
        'Can be slightly more reactive / noisier than DEMA',
      ],
      recommendedTimeframes: '15m–1D+ (very strong on daily)',
      dataNotes: [
        'Requires 3x warmup of base EMA length due to triple nesting',
      ],
      relatedIndicators: ['ema', 'dema', 'zlma'],
      panelType: 'overlay',
      quickWhy: 'Ultra-fast confirmation. The most sensitive version of DEMA.',
      quickAnalogy: 'A fighter jet following the price so closely it almost touches the candles.',
      quickImpact: 'Best for hyper-volatile markets where direction changes in the blink of an eye.',
      checkQuestion: 'If the TEMA starts pointing down, does that mean the trend is definitely over?',
      checkAnswer: 'Not necessarily — it is so sensitive it might just be a small hiccup',
      professionalRef: 'Patrick Mulloy (1994)',
      timeframeBehavior: 'On scalping timeframes, the 15-minute delay makes TEMA dangerous; the "spike" you see is already 15 minutes old.',
    },
    {
      name: 'wma',
      displayName: 'Weighted Moving Average (WMA)',
      formulaLatex: '\\text{WMA}_t(n)=\\frac{\\sum_{i=0}^{n-1}(n-i)\\cdot C_{t-i}}{\\sum_{k=1}^{n}k}',
      description: 'Applies larger weights to recent bars, making it more responsive than SMA.',
      library: 'pandas-ta (ta.wma)',
      outputColumns: ['wma_{length}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Faster trend identification than SMA',
        'Useful for short-term trend tracking',
        'Works well for crossover systems',
      ],
      recommendedTimeframes: '1m–4h (strong on intraday)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['sma', 'ema', 'hma'],
      panelType: 'overlay',
      quickWhy: 'Ensures today\'s news is more important than last week\'s.',
      quickAnalogy: 'Like a "Trending Now" list — what people said 5 minutes ago matters more than yesterday.',
      quickImpact: 'Stays closer to the price than an SMA, making it a better tracker for active traders.',
      professionalRef: 'Popularized by Steven Achelis',
      timeframeBehavior: 'Heavy impact of 15-minute delay since the highest weight is on a candle that is actually 15 minutes old.',
    },
    {
      name: 'hma',
      displayName: 'Hull Moving Average (HMA)',
      formulaLatex: '\\text{HMA}(n)=WMA(2\\cdot WMA(n/2)-WMA(n),\\sqrt{n})',
      description: 'Reduces lag while keeping smoothness, often producing visually clean trend lines.',
      library: 'pandas-ta (ta.hma)',
      outputColumns: ['hma_{length}'],
      defaultParams: 'length = 55',
      interpretation: [
        'Excellent trend filter',
        'Often used as "signal line" for trend changes',
        'Commonly used in algorithmic trend systems',
      ],
      recommendedTimeframes: '4h–1D (excellent); can be choppy on 5m–1h',
      dataNotes: [
        'Warmup depends on sqrt(length) inner WMA',
      ],
      relatedIndicators: ['wma', 'ema', 'kama'],
      panelType: 'overlay',
      quickWhy: 'Be smooth and fast at the same time — usually you have to pick one.',
      quickAnalogy: 'A silk ribbon flowing in the wind. It follows the wind (price) perfectly without any sharp, jagged edges.',
      quickImpact: 'Clear "Go / No-Go" signals; the line changes color when the trend shifts.',
      professionalRef: 'Alan Hull (2005)',
      timeframeBehavior: '"Beautiful" but deceptive with 15-minute delays. It may look like a smooth uptrend while a crash is happening in the "blind spot."',
    },
    {
      name: 'kama',
      displayName: 'Kaufman Adaptive Moving Average (KAMA)',
      formulaLatex: 'ER=\\frac{|C_t-C_{t-n}|}{\\sum_{i=1}^{n}|C_{t-i}-C_{t-i-1}|}, \\quad SC=(ER\\cdot(fastSC-slowSC)+slowSC)^2, \\quad KAMA_t = KAMA_{t-1} + SC\\cdot(C_t-KAMA_{t-1})',
      description: 'Adapts smoothing based on market efficiency: smooth during choppy markets, fast during trending markets.',
      library: 'pandas-ta (ta.kama)',
      outputColumns: ['kama_{length}'],
      defaultParams: 'length = 10',
      interpretation: [
        'Excellent adaptive trend line',
        'Reduces false signals during sideways conditions',
        'Works well as a regime detector',
      ],
      recommendedTimeframes: 'All timeframes (especially good for noisy intraday)',
      dataNotes: [
        'Depends heavily on consistent candle spacing',
      ],
      relatedIndicators: ['ema', 'alma', 'zlma'],
      panelType: 'overlay',
      quickWhy: 'An average with its own "intelligence." Speeds up in trends, slows down during chop.',
      quickAnalogy: 'Adaptive cruise control that speeds up on the highway but slows down in heavy city traffic.',
      quickImpact: 'Helps you avoid getting fooled by small, meaningless price jumps.',
      professionalRef: 'Perry Kaufman (1995)',
      timeframeBehavior: 'Excellent for daily charts. The 15-minute delay is less problematic as it filters for "efficiency" over time.',
    },
    {
      name: 'zlma',
      displayName: 'Zero Lag Moving Average (ZLMA)',
      formulaLatex: 'ZLMA = EMA(2C_t - C_{t-lag}), \\quad lag=\\frac{n-1}{2}',
      description: 'Attempts to reduce lag by compensating for the inherent delay in moving averages.',
      library: 'pandas-ta (ta.zlma)',
      outputColumns: ['zlma_{length}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Faster trend signals than standard EMA',
        'Higher false positives in sideways markets',
        'Useful for short-term trend detection',
      ],
      recommendedTimeframes: '1m–1h (strong on intraday)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['ema', 'dema', 'tema'],
      panelType: 'overlay',
      quickWhy: '"Predict" the price by removing the delay found in all other averages.',
      quickAnalogy: 'A forecast telling you where the storm will be in 10 minutes, rather than where it was 10 minutes ago.',
      quickImpact: 'Crosses the price earlier than any other average, giving you a head start.',
      professionalRef: 'John Ehlers and Ric Way',
      timeframeBehavior: 'Hyper-reactive. Very risky with a 15-minute delay because the "projection" is based on stale momentum data.',
    },
    {
      name: 'rma',
      displayName: 'Running Moving Average / Wilder Smoothing (RMA)',
      formulaLatex: 'RMA_t = \\frac{(n-1)\\cdot RMA_{t-1}+C_t}{n}',
      description: 'Wilder\'s smoothing method, used internally by ATR, RSI, and ADX.',
      library: 'pandas-ta (ta.rma)',
      outputColumns: ['rma_{length}'],
      defaultParams: 'length = 14',
      interpretation: [
        'A smoothing baseline for volatility and momentum indicators',
        'Slightly slower than EMA with equivalent period',
      ],
      recommendedTimeframes: 'All timeframes',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['ema', 'atr', 'rsi'],
      panelType: 'overlay',
      quickWhy: 'The stable foundation used to calculate other famous tools like RSI.',
      quickAnalogy: 'The foundation of a house. You don\'t see it, but everything else relies on it being stable and slow-moving.',
      quickImpact: 'Provides a very smooth, long-term view of "Fair Value."',
      professionalRef: 'J. Welles Wilder Jr. (1978)',
      timeframeBehavior: 'Minimal impact from 15-minute delay due to heavy smoothing.',
    },
    {
      name: 'alma',
      displayName: 'Arnaud Legoux Moving Average (ALMA)',
      formulaLatex: '\\text{ALMA}(n) = \\sum_{i=0}^{n-1} w_i \\cdot C_{t-i}, \\quad w_i = e^{-\\frac{(i - m)^2}{2s^2}}',
      description: 'Uses a Gaussian distribution weighting function for smoothing. Very smooth and low-lag.',
      library: 'pandas-ta (ta.alma)',
      outputColumns: ['alma_{length}'],
      defaultParams: 'length = 20, offset = 0.85, sigma = 6',
      interpretation: [
        'Very smooth and low-lag moving average',
        'Useful for signal extraction in medium-term trend systems',
        'Offset controls responsiveness, sigma controls smoothness',
      ],
      recommendedTimeframes: '15m–1D+ (excellent on daily)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['ema', 'kama', 'hma'],
      panelType: 'overlay',
      quickWhy: 'The smoothest line without the "overshoot" common in fast averages.',
      quickAnalogy: 'A cinematographer using a steadicam — even if the cameraman is running, the footage looks perfectly smooth.',
      quickImpact: 'The most trustworthy line for identifying a steady trend.',
      professionalRef: 'Arnaud Legoux and Dimitrios Kouzis-Loukas (2009)',
      timeframeBehavior: 'Highly reliable for 15-minute charts; filters delayed noise better than EMAs.',
    },
    {
      name: 'bbands',
      displayName: 'Bollinger Bands',
      formulaLatex: '\\text{Mid} = \\text{SMA}(C, n), \\quad \\text{Upper} = \\text{Mid} + k\\sigma_n, \\quad \\text{Lower} = \\text{Mid} - k\\sigma_n',
      description: 'Measures volatility with bands k standard deviations around an SMA. Outputs 5 columns: lower band, mid (basis), upper band, bandwidth, and %B (percent B).',
      library: 'pandas-ta (ta.bbands)',
      outputColumns: ['bbl_{n}_{k}', 'bbm_{n}_{k}', 'bbu_{n}_{k}', 'bbb_{n}_{k}', 'bbp_{n}_{k}'],
      defaultParams: 'length = 20, std = 2.0',
      interpretation: [
        'Price touching upper band → potential overbought / strong uptrend',
        'Price touching lower band → potential oversold / strong downtrend',
        'Band squeeze (narrow bandwidth) → volatility contraction, breakout pending',
        '%B > 1 = above upper band, %B < 0 = below lower band',
      ],
      recommendedTimeframes: '5m–1D (excellent on 1h–4h)',
      dataNotes: [
        'Requires `length` warmup bars',
        'Bandwidth and %B are useful for quantitative systems',
      ],
      relatedIndicators: ['kc', 'squeeze', 'sma'],
      panelType: 'overlay',
      quickWhy: 'See the market\'s "Mood Swing" — how far price is stretching from normal.',
      quickAnalogy: 'A rubber band. The further you stretch it, the more likely it is to snap back to the center.',
      quickImpact: 'When the bands get tight (a "Squeeze"), a massive move is usually coming soon.',
      checkQuestion: 'If price hits the top band and stays there, is the market "too expensive" or "very strong"?',
      checkAnswer: 'Usually very strong momentum',
      professionalRef: 'John Bollinger (1983)',
      timeframeBehavior: '15-minute delay is critical; if a breakout occurs in real-time, the app won\'t show it for 15 minutes.',
    },
    {
      name: 'supertrend',
      displayName: 'Supertrend',
      formulaLatex: '\\text{Up} = \\frac{H+L}{2} + m \\cdot \\text{ATR}(n), \\quad \\text{Down} = \\frac{H+L}{2} - m \\cdot \\text{ATR}(n)',
      description: 'Trend-following indicator based on ATR. Flips between support (uptrend) and resistance (downtrend). Outputs 4 columns: trend value, direction (1/-1), long (support), short (resistance). ATR uses RMA smoothing.',
      library: 'pandas-ta (ta.supertrend)',
      outputColumns: ['supert_{n}_{m}', 'supertd_{n}_{m}', 'supertl_{n}_{m}', 'superts_{n}_{m}'],
      defaultParams: 'length = 10, multiplier = 3.0',
      interpretation: [
        'Direction = 1 → uptrend (price above support line)',
        'Direction = -1 → downtrend (price below resistance line)',
        'Trend flips are common entry/exit signals',
        'Higher multiplier = fewer whipsaws but later entries',
      ],
      recommendedTimeframes: '15m–1D (excellent on 1h–4h)',
      dataNotes: [
        'First few bars may show NaN while ATR warms up',
        'Direction flips can produce gaps in the trend line',
      ],
      relatedIndicators: ['atr', 'psar', 'ema'],
      panelType: 'overlay',
      quickWhy: 'A simple "Stoplight" for trades — exactly when to be "In" or "Out."',
      quickAnalogy: 'A trail marker on a hike. Green path = safe. Red = you\'ve gone off-trail.',
      quickImpact: 'Automatically provides a level for your stop-loss.',
      professionalRef: 'Olivier Seban',
      timeframeBehavior: 'Effective on 15m and Daily charts. The 15-minute delay makes signals reactive; price may have already moved 1% before the color flips.',
    },
    {
      name: 'vwap',
      displayName: 'Volume Weighted Average Price (VWAP)',
      formulaLatex: 'VWAP = \\frac{\\sum (TP \\cdot V)}{\\sum V}, \\quad TP = \\frac{H+L+C}{3}',
      description: 'Represents the "fair value" price weighted by volume. Must reset at session boundary (daily).',
      library: 'pandas-ta (ta.vwap)',
      outputColumns: ['vwap'],
      defaultParams: 'Session-based reset (implicit)',
      interpretation: [
        'Price above VWAP → bullish intraday bias',
        'Price below VWAP → bearish intraday bias',
        'Common mean-reversion anchor for institutional traders',
      ],
      recommendedTimeframes: 'Intraday only (1m–30m best). Not meaningful for multi-day unless anchored.',
      dataNotes: [
        'Must reset at session boundary (daily)',
        'Very sensitive to missing volume candles',
        'Volume-dependent — unreliable with zero-volume bars',
        'Behaves differently in extended hours vs RTH',
      ],
      relatedIndicators: ['ad', 'cmf', 'mfi'],
      panelType: 'overlay',
      quickWhy: 'Find the "True Cost" today by combining price and how many people were buying.',
      quickAnalogy: 'If 1 person buys coffee for $10 and 100 people buy it for $2, the "real" average isn\'t $6 — it\'s $2.',
      quickImpact: '"Big Money" uses this. Buying below this line is usually a "good deal" for the day.',
      professionalRef: 'Berkowitz, Logue, and Noser (1988)',
      timeframeBehavior: 'Only valid for intraday. The 15-minute delay is a severe handicap as it ignores the most recent high-volume action.',
    },
    {
      name: 'psar',
      displayName: 'Parabolic SAR',
      formulaLatex: '\\text{SAR}_{t+1} = \\text{SAR}_t + \\text{AF} \\cdot (\\text{EP} - \\text{SAR}_t)',
      description: 'Trailing stop-and-reverse system. Dots above price = downtrend, below = uptrend. AF accelerates toward the extreme point (EP).',
      library: 'pandas-ta (ta.psar)',
      outputColumns: ['psarl_{af}_{max}', 'psars_{af}_{max}', 'psaraf_{af}_{max}', 'psarr_{af}_{max}'],
      defaultParams: 'af0 = 0.02, af = 0.02, max_af = 0.2',
      interpretation: [
        'Dots below price → uptrend (use as trailing stop)',
        'Dots above price → downtrend (use as trailing stop)',
        'Reversal when price crosses SAR dots',
        'Best in trending markets — frequent whipsaws in sideways',
      ],
      recommendedTimeframes: '15m–1D (works best in trending conditions)',
      dataNotes: [
        'First bar may be NaN',
        'Sensitive to gap openings',
      ],
      relatedIndicators: ['supertrend', 'atr', 'adx'],
      panelType: 'overlay',
      quickWhy: 'Your "Trailing Security Guard." Follows price up and tells you the second the trend is over.',
      quickAnalogy: 'A dog on a leash that gets shorter as you get closer to home. Eventually you hit the end and must stop.',
      quickImpact: 'Tells you exactly where to exit a trade to protect your profits.',
      professionalRef: 'J. Welles Wilder Jr. (1978)',
      timeframeBehavior: 'Dangerous with 15-minute delay; the real price may hit your stop level 15 minutes before the app shows it.',
    },
    {
      name: 'kc',
      displayName: 'Keltner Channel',
      formulaLatex: '\\text{Mid} = EMA(C, n), \\quad \\text{Upper} = Mid + k\\cdot ATR(n), \\quad \\text{Lower} = Mid - k\\cdot ATR(n)',
      description: 'Volatility bands based on ATR, often smoother than Bollinger Bands.',
      library: 'pandas-ta (ta.kc)',
      outputColumns: ['kcl_{n}_{k}', 'kcb_{n}_{k}', 'kcu_{n}_{k}'],
      defaultParams: 'length = 20, scalar = 1.5',
      interpretation: [
        'Break above upper band → strong bullish expansion',
        'Inside channel → neutral consolidation',
        'Channel slope indicates trend direction',
      ],
      recommendedTimeframes: '5m–1D (excellent trend channel on 4h–1D)',
      dataNotes: [
        'Requires `length` warmup for both EMA and ATR',
      ],
      relatedIndicators: ['bbands', 'atr', 'squeeze'],
      panelType: 'overlay',
      quickWhy: 'A calmer version of Bollinger Bands — a tunnel that doesn\'t overreact to every spike.',
      quickAnalogy: 'A riverbed. Price stays within the banks most of the time. If it overflows, something big is happening.',
      quickImpact: 'Best for finding "Bargain Entries" when price dips to the middle during an uptrend.',
      professionalRef: 'Chester Keltner (1960); revised by Linda Raschke',
      timeframeBehavior: 'Best on 15m charts. Delay makes bands appear "tighter" than reality during spikes.',
    },
    {
      name: 'donchian',
      displayName: 'Donchian Channel',
      formulaLatex: '\\text{Upper} = \\max(H_{t-n+1},...,H_t), \\quad \\text{Lower} = \\min(L_{t-n+1},...,L_t), \\quad \\text{Mid} = \\frac{Upper + Lower}{2}',
      description: 'Represents the highest high and lowest low over a rolling window. Used in Turtle Trading systems.',
      library: 'pandas-ta (ta.donchian)',
      outputColumns: ['dcl_{n}', 'dcm_{n}', 'dcu_{n}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Breakout above upper channel → trend continuation / new trend',
        'Breakout below lower channel → bearish breakout',
        'Common in Turtle Trading systems',
      ],
      recommendedTimeframes: '1h–1W (excellent breakout indicator on 4h–1D)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['kc', 'bbands', 'atr'],
      panelType: 'overlay',
      quickWhy: 'Shows the "Ultimate High" and "Ultimate Low" of the last few days.',
      quickAnalogy: 'A record book showing the all-time high score for the current "game" (period).',
      quickImpact: 'Helps find breakouts — when price breaks a record high, it often keeps going.',
      professionalRef: 'Richard Donchian',
      timeframeBehavior: 'Very robust. 15-minute delay is less of an issue because a 20-day high is unlikely to change every minute.',
    },

    // ═══════════════════════════════════════════════════════════
    //  SUB-PANEL INDICATORS
    // ═══════════════════════════════════════════════════════════
    {
      name: 'macd',
      displayName: 'MACD (Moving Average Convergence Divergence)',
      formulaLatex: '\\text{MACD} = \\text{EMA}(C, f) - \\text{EMA}(C, s), \\quad \\text{Signal} = \\text{EMA}(\\text{MACD}, g), \\quad \\text{Hist} = \\text{MACD} - \\text{Signal}',
      description: 'Captures the relationship between two EMAs. Outputs 3 columns: MACD line, histogram, and signal line. Rising histogram = strengthening momentum.',
      library: 'pandas-ta (ta.macd)',
      outputColumns: ['macd_{f}_{s}_{g}', 'macdh_{f}_{s}_{g}', 'macds_{f}_{s}_{g}'],
      defaultParams: 'fast = 12, slow = 26, signal = 9',
      interpretation: [
        'MACD crossing above signal → bullish',
        'MACD crossing below signal → bearish',
        'Histogram rising → momentum increasing',
        'Divergence between price and MACD → potential reversal',
      ],
      recommendedTimeframes: '15m–1D (excellent on 1h–4h)',
      dataNotes: [
        'Requires `slow` warmup bars before producing valid values',
      ],
      relatedIndicators: ['ema', 'rsi', 'tsi'],
      panelType: 'sub-panel',
      quickWhy: 'Feel the "momentum" behind a move.',
      quickAnalogy: 'A snowball rolling down a hill. MACD tells you if it\'s getting bigger and faster or starting to melt.',
      quickImpact: 'When the two lines cross, it\'s like a "Starting Pistol" for a new move.',
      checkQuestion: 'If MACD bars are shrinking while price is rising, is the move getting stronger or weaker?',
      checkAnswer: 'Weaker — this is a warning',
      professionalRef: 'Gerald Appel (1970s)',
      timeframeBehavior: 'Delayed Histogram can show "Momentum Loss" while the real market is exploding.',
    },
    {
      name: 'rsi',
      displayName: 'Relative Strength Index (RSI)',
      formulaLatex: '\\text{RSI} = 100 - \\frac{100}{1 + \\frac{\\text{AvgGain}(n)}{\\text{AvgLoss}(n)}}',
      description: 'Measures speed and magnitude of price changes. Uses Wilder\'s RMA smoothing by default. Values above 70 = overbought, below 30 = oversold.',
      library: 'pandas-ta (ta.rsi, mamode="rma")',
      outputColumns: ['rsi_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'RSI > 70 → overbought (potential reversal or strong uptrend)',
        'RSI < 30 → oversold (potential reversal or strong downtrend)',
        'RSI divergence from price signals weakening momentum',
        'Centerline (50) crossover used as trend filter',
      ],
      recommendedTimeframes: '5m–1D (excellent on all common timeframes)',
      dataNotes: [
        'Requires `length` warmup bars (Wilder smoothing)',
      ],
      relatedIndicators: ['stochrsi', 'mfi', 'cci'],
      panelType: 'sub-panel',
      quickWhy: 'See if a stock is "Overstretched" or exhausted.',
      quickAnalogy: 'Pulling a rubber band to the "70" mark — very tight, wants to snap back (Overbought). At "30," stretched the other way (Oversold).',
      quickImpact: 'Tells you when it\'s "Dangerous to Buy" because everyone else already bought.',
      checkQuestion: 'If RSI is at 85, is it a good time to start a long-term investment?',
      checkAnswer: 'Probably not — wait for a dip',
      professionalRef: 'J. Welles Wilder Jr. (1978)',
      timeframeBehavior: '15-minute delay is a major risk; RSI might show "35" while real price has already hit "20" and bounced.',
    },
    {
      name: 'adx',
      displayName: 'Average Directional Index (ADX)',
      formulaLatex: '\\text{ADX} = \\text{RMA}\\!\\left(\\frac{|{+DI} - {-DI}|}{+DI + {-DI}} \\times 100,\\; n\\right)',
      description: 'Measures trend strength (not direction). Outputs ADX, +DI, and -DI. Uses tvmode=True for TradingView compatibility. ADX > 25 = strong trend.',
      library: 'pandas-ta (ta.adx, tvmode=True)',
      outputColumns: ['adx_{n}', 'dmp_{n}', 'dmn_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'ADX > 25 → strong trend',
        'ADX < 20 → weak/no trend (range-bound)',
        '+DI above -DI → bullish pressure',
        '-DI above +DI → bearish pressure',
      ],
      recommendedTimeframes: '1h–1D (excellent for trend strength confirmation)',
      dataNotes: [
        'Requires ~2x `length` warmup bars due to nested smoothing',
      ],
      relatedIndicators: ['atr', 'rsi', 'supertrend'],
      panelType: 'sub-panel',
      quickWhy: 'See if a trend is "Real" or just meaningless zig-zagging.',
      quickAnalogy: 'A wind speed meter. Doesn\'t care if wind blows North or South — just how hard it\'s blowing.',
      quickImpact: 'Saves you from trading in "boring" markets where nothing is happening.',
      professionalRef: 'J. Welles Wilder Jr. (1978)',
      timeframeBehavior: '"Slow" indicator; 15-minute delay is negligible.',
    },
    {
      name: 'atr',
      displayName: 'Average True Range (ATR)',
      formulaLatex: '\\text{TR} = \\max(H-L,\\; |H - C_{t-1}|,\\; |L - C_{t-1}|), \\quad \\text{ATR} = \\text{RMA}(\\text{TR}, n)',
      description: 'Measures volatility using the true range of each bar. ATR is the RMA-smoothed average of true range. Used internally by Supertrend and other indicators.',
      library: 'pandas-ta (ta.atr)',
      outputColumns: ['atr_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'Rising ATR → volatility expansion',
        'Falling ATR → volatility contraction',
        'Common for position sizing (risk per trade = ATR × multiplier)',
        'Used as input to Supertrend, Keltner Channels',
      ],
      recommendedTimeframes: 'All timeframes',
      dataNotes: [
        'Requires `length` warmup bars',
        'Sensitive to gap openings (true range includes previous close)',
      ],
      relatedIndicators: ['natr', 'supertrend', 'kc'],
      panelType: 'sub-panel',
      quickWhy: 'Measure "Volatility" — how much a stock jumps around.',
      quickAnalogy: 'The daily range of a forest fire. Does it move 1 mile a day or 10 miles? Helps you know how much space to give your trade.',
      quickImpact: 'Helps set "smart" stop-losses so you don\'t get kicked out by a normal daily wiggle.',
      professionalRef: 'J. Welles Wilder Jr. (1978)',
      timeframeBehavior: 'Delay means ATR is based on "Stale Volatility."',
    },
    {
      name: 'stoch',
      displayName: 'Stochastic Oscillator',
      formulaLatex: '\\%K = \\frac{C - L_n}{H_n - L_n} \\times 100, \\quad \\%D = \\text{SMA}(\\%K, d)',
      description: 'Measures where the close sits in the recent high-low range. %K is the fast line, %D is the signal. Outputs 2 columns.',
      library: 'pandas-ta (ta.stoch)',
      outputColumns: ['stochk_{k}_{d}', 'stochd_{k}_{d}'],
      defaultParams: 'k = 14, d = 3',
      interpretation: [
        'K/D above 80 → overbought',
        'K/D below 20 → oversold',
        '%K crossing above %D → bullish signal',
        '%K crossing below %D → bearish signal',
      ],
      recommendedTimeframes: '5m–4h (strong intraday oscillator)',
      dataNotes: [
        'Requires `k` warmup bars',
      ],
      relatedIndicators: ['stochrsi', 'rsi', 'willr'],
      panelType: 'sub-panel',
      quickWhy: 'See where today\'s price sits compared to recent highs and lows.',
      quickAnalogy: 'A tide gauge at the beach. Is the water at the high-tide mark or low-tide mark?',
      quickImpact: 'When the "High Tide" turns back, it\'s often a signal to sell.',
      professionalRef: 'George Lane (1950s)',
      timeframeBehavior: 'Prone to whipsaws on 1m charts. 15-minute delay can cause you to miss a crossover entirely.',
    },
    {
      name: 'stochrsi',
      displayName: 'Stochastic RSI',
      formulaLatex: '\\text{StochRSI}=\\frac{RSI-\\min(RSI)}{\\max(RSI)-\\min(RSI)}',
      description: 'Applies a stochastic oscillator calculation to RSI, producing a faster oscillator. Outputs K and D lines.',
      library: 'pandas-ta (ta.stochrsi)',
      outputColumns: ['stochrsi_k_{n}', 'stochrsi_d_{n}'],
      defaultParams: 'length = 14, rsi_length = 14, k = 3, d = 3',
      interpretation: [
        'Values near 0 → oversold',
        'Values near 1 → overbought',
        'K/D crossovers generate signals',
        'Faster than regular RSI — more signals but more noise',
      ],
      recommendedTimeframes: '1m–4h (very strong but high signal frequency on lower timeframes)',
      dataNotes: [
        'Requires `length + rsi_length` warmup bars',
      ],
      relatedIndicators: ['rsi', 'stoch', 'willr'],
      panelType: 'sub-panel',
      quickWhy: 'An ultra-sensitive version of RSI — finds "Extremes of the Extremes."',
      quickAnalogy: 'A microscope looking at the RSI. It reveals tiny shifts the normal eye misses.',
      quickImpact: 'Great for finding the "Exact Top" or "Exact Bottom" of a quick move.',
      professionalRef: 'Tushar Chande and Stanley Kroll (1994)',
      timeframeBehavior: 'So sensitive it spends most of its time at 0 or 100. The 15-minute delay is its "Achilles Heel."',
    },
    {
      name: 'obv',
      displayName: 'On Balance Volume (OBV)',
      formulaLatex: '\\text{OBV}_t = \\text{OBV}_{t-1} + \\begin{cases} V_t & C_t > C_{t-1} \\\\ -V_t & C_t < C_{t-1} \\\\ 0 & \\text{otherwise} \\end{cases}',
      description: 'Cumulative volume indicator. Rising OBV confirms uptrend; divergence between OBV and price signals potential reversal. No configurable parameters.',
      library: 'pandas-ta (ta.obv)',
      outputColumns: ['obv'],
      defaultParams: 'None',
      interpretation: [
        'Rising OBV with rising price → healthy uptrend confirmed',
        'Falling OBV while price rises → bearish divergence',
        'OBV breakout before price breakout → leading signal',
      ],
      recommendedTimeframes: '1h–1D+ (noisy on very short timeframes)',
      dataNotes: [
        'Cumulative — can drift heavily over long history',
        'Volume-dependent — unreliable with zero-volume bars',
        'Behaves differently in extended hours vs RTH',
      ],
      relatedIndicators: ['ad', 'cmf', 'mfi'],
      panelType: 'sub-panel',
      quickWhy: 'The "Underground Truth" — tracks if smart money is actually showing up.',
      quickAnalogy: 'A turnstile at a stadium. Doesn\'t matter if ticket prices go up or down; it just counts how many people walked in.',
      quickImpact: 'Price dropping but OBV rising? Smart money is "Buying the Dip."',
      professionalRef: 'Joseph Granville (1963)',
      timeframeBehavior: 'Non-impactful 15-minute delay for this long-term cumulative line.',
    },
    {
      name: 'cci',
      displayName: 'Commodity Channel Index (CCI)',
      formulaLatex: '\\text{CCI} = \\frac{\\text{TP} - \\text{SMA}(\\text{TP}, n)}{0.015 \\cdot \\text{MAD}(\\text{TP}, n)}, \\quad \\text{TP} = \\frac{H+L+C}{3}',
      description: 'Measures deviation from the statistical mean. Values above +100 = overbought, below -100 = oversold.',
      library: 'pandas-ta (ta.cci)',
      outputColumns: ['cci_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'CCI > +100 → overbought / strong bullish momentum',
        'CCI < -100 → oversold / strong bearish momentum',
        'Zero-line crossover used as trend filter',
        'Divergence with price signals weakening momentum',
      ],
      recommendedTimeframes: '15m–1D (strong on 1h–4h)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['rsi', 'stoch', 'mfi'],
      panelType: 'sub-panel',
      quickWhy: 'See when a stock acts "Weird" compared to its history.',
      quickAnalogy: 'A student\'s grades. If they usually get 80s and suddenly get a 20, CCI screams that something is wrong.',
      quickImpact: 'Spots "crashes" or "moonshots" before they become obvious.',
      professionalRef: 'Donald Lambert (1980)',
      timeframeBehavior: 'Effective for Mean Reversion on Hourly charts.',
    },
    {
      name: 'willr',
      displayName: 'Williams %R',
      formulaLatex: '\\%R = -100\\cdot\\frac{HH(n)-C}{HH(n)-LL(n)}',
      description: 'Momentum oscillator measuring close location relative to recent high-low range.',
      library: 'pandas-ta (ta.willr)',
      outputColumns: ['willr_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        '-20 to 0 → overbought',
        '-80 to -100 → oversold',
        'Useful for mean reversion and turning points',
        'Essentially the inverse of the Stochastic oscillator',
      ],
      recommendedTimeframes: '1m–4h (strong intraday)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['stoch', 'stochrsi', 'rsi'],
      panelType: 'sub-panel',
      quickWhy: 'A "flipped" version of the Stochastic focusing strictly on highs.',
      quickAnalogy: 'A thermometer measuring how far you are below the boiling point.',
      quickImpact: 'Excellent for catching "failed rallies" when price tries to hit a new high but fails.',
      professionalRef: 'Larry Williams',
      timeframeBehavior: '15-minute delay often masks the "Overbought" signal until the drop has started.',
    },
    {
      name: 'roc',
      displayName: 'Rate of Change (ROC)',
      formulaLatex: '\\text{ROC}=\\frac{C_t-C_{t-n}}{C_{t-n}}\\times 100',
      description: 'Measures the percentage change from n bars ago.',
      library: 'pandas-ta (ta.roc)',
      outputColumns: ['roc_{n}'],
      defaultParams: 'length = 12',
      interpretation: [
        'ROC > 0 → bullish momentum',
        'ROC < 0 → bearish momentum',
        'ROC crossing above 0 often signals trend initiation',
      ],
      recommendedTimeframes: '15m–1D (all timeframes, particularly useful on 1h)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['mom', 'rsi', 'tsi'],
      panelType: 'sub-panel',
      quickWhy: 'Measure the "Speed Limit" of a stock.',
      quickAnalogy: 'A car\'s speedometer. Is the stock going 10 mph or 100 mph?',
      quickImpact: 'If the stock slows from 100 to 80 mph, ROC drops, warning the "race" is ending.',
      professionalRef: 'Classical momentum theory',
      timeframeBehavior: '15-minute delay makes "Current Speed" essentially a historical record.',
    },
    {
      name: 'mom',
      displayName: 'Momentum (MOM)',
      formulaLatex: '\\text{MOM}=C_t-C_{t-n}',
      description: 'Absolute price change over n periods. Measures raw speed of movement.',
      library: 'pandas-ta (ta.mom)',
      outputColumns: ['mom_{n}'],
      defaultParams: 'length = 10',
      interpretation: [
        'Positive MOM → upward momentum',
        'Negative MOM → downward momentum',
        'Works best with smoothing or normalization for signal clarity',
      ],
      recommendedTimeframes: 'All timeframes (best paired with other confirmation)',
      dataNotes: [
        'Requires `length` warmup bars',
        'Not normalized — absolute value depends on price level',
      ],
      relatedIndicators: ['roc', 'rsi', 'tsi'],
      panelType: 'sub-panel',
      quickWhy: 'Similar to ROC, but measures "Total Distance" rather than percentage.',
      quickAnalogy: 'Measuring how many feet a sprinter ran in 10 seconds.',
      quickImpact: 'Shows the pure "Force" of the buyers.',
      professionalRef: 'Traditional TA theory',
      timeframeBehavior: 'Results in "Lagged Velocity" due to feed delay.',
    },
    {
      name: 'natr',
      displayName: 'Normalized ATR (NATR)',
      formulaLatex: '\\text{NATR}=\\frac{ATR(n)}{C_t}\\times 100',
      description: 'Expresses ATR as a percentage of price, making volatility comparable across instruments.',
      library: 'pandas-ta (ta.natr)',
      outputColumns: ['natr_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'Rising NATR → volatility expansion',
        'Useful for risk sizing across different-priced instruments',
        'Can be used as a regime detector (high vol vs low vol)',
      ],
      recommendedTimeframes: 'All timeframes (very useful intraday for risk control)',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['atr', 'bbands', 'kc'],
      panelType: 'sub-panel',
      quickWhy: 'Compare volatility of two different stocks (e.g. Apple vs. a penny stock).',
      quickAnalogy: 'Comparing a tall man to a short man. A 1-foot jump for a short man is huge; for a tall man, it\'s a small hop.',
      quickImpact: 'Tells you which stocks in your list are the "craziest" today.',
      professionalRef: 'John Forman (2006)',
      timeframeBehavior: 'Delay impacts both components (ATR and Price).',
    },
    {
      name: 'ad',
      displayName: 'Accumulation/Distribution Line (AD)',
      formulaLatex: 'CLV=\\frac{(C-L)-(H-C)}{H-L}, \\quad AD_t=AD_{t-1} + CLV\\cdot V',
      description: 'Estimates buying vs selling pressure using price location within the bar combined with volume.',
      library: 'pandas-ta (ta.ad)',
      outputColumns: ['ad'],
      defaultParams: 'None (cumulative)',
      interpretation: [
        'Rising AD with rising price → healthy uptrend',
        'Falling AD while price rises → bearish divergence',
        'Strong divergence tool for spotting distribution',
      ],
      recommendedTimeframes: '4h–1W (noisy on intraday, excellent on daily+)',
      dataNotes: [
        'Cumulative — can drift heavily over long history',
        'Volume-dependent — unreliable with zero-volume bars',
        'Behaves differently in extended hours vs RTH',
      ],
      relatedIndicators: ['obv', 'cmf', 'mfi'],
      panelType: 'sub-panel',
      quickWhy: 'See what the "Big Fish" (institutions) are doing behind the scenes.',
      quickAnalogy: 'A bank account for the stock. If price is flat but this line goes up, money is being "deposited."',
      quickImpact: 'Warns you of a breakout before it happens.',
      professionalRef: 'Marc Chaikin',
      timeframeBehavior: '15-minute delay is a non-factor for this long-term cumulative line.',
    },
    {
      name: 'cmf',
      displayName: 'Chaikin Money Flow (CMF)',
      formulaLatex: 'CMF(n)=\\frac{\\sum_{i=0}^{n-1}(CLV_i\\cdot V_i)}{\\sum_{i=0}^{n-1}V_i}',
      description: 'Measures accumulation/distribution over a rolling window.',
      library: 'pandas-ta (ta.cmf)',
      outputColumns: ['cmf_{n}'],
      defaultParams: 'length = 20',
      interpretation: [
        'CMF > 0 → accumulation (bullish)',
        'CMF < 0 → distribution (bearish)',
        'Strong divergence indicator vs price',
      ],
      recommendedTimeframes: '1D+ (best on daily; works but noisy intraday)',
      dataNotes: [
        'Requires `length` warmup bars',
        'Volume-dependent — unreliable with zero-volume bars',
      ],
      relatedIndicators: ['ad', 'obv', 'mfi'],
      panelType: 'sub-panel',
      quickWhy: 'See if the "Big Fish" are still buying over several weeks.',
      quickAnalogy: 'A popularity contest lasting 21 days. Shows if people are consistently voting "Yes" with their money.',
      quickImpact: 'If price goes up but CMF stays below zero, the move is a "Fakeout."',
      professionalRef: 'Marc Chaikin',
      timeframeBehavior: 'Volume "confirmation" is based on stale data.',
    },
    {
      name: 'mfi',
      displayName: 'Money Flow Index (MFI)',
      formulaLatex: 'TP=\\frac{H+L+C}{3}, \\quad MF=TP\\cdot V, \\quad MFI = 100 - \\frac{100}{1 + \\frac{\\sum MF^+}{\\sum MF^-}}',
      description: 'RSI-like oscillator but volume-weighted. Often called "volume RSI".',
      library: 'pandas-ta (ta.mfi)',
      outputColumns: ['mfi_{n}'],
      defaultParams: 'length = 14',
      interpretation: [
        'MFI > 80 → overbought',
        'MFI < 20 → oversold',
        'Divergence with price signals potential reversal',
        'More reliable than RSI when volume data is clean',
      ],
      recommendedTimeframes: '4h–1W (noisy intraday; excellent on daily)',
      dataNotes: [
        'Requires `length` warmup bars',
        'Volume-dependent — unreliable with zero-volume bars',
        'Behaves differently in extended hours vs RTH',
      ],
      relatedIndicators: ['rsi', 'cmf', 'obv'],
      panelType: 'sub-panel',
      quickWhy: 'RSI but with volume included — measures how much money actually moves price.',
      quickAnalogy: 'A concert. RSI shows how loud the music is; MFI shows how many people are in the stadium cheering.',
      quickImpact: 'Much harder to "fake" than standard RSI.',
      professionalRef: 'Gene Quong and Avrum Soudack',
      timeframeBehavior: 'Feed delay impacts the volume input, which is critical here.',
    },
    {
      name: 'tsi',
      displayName: 'True Strength Index (TSI)',
      formulaLatex: 'TSI = 100\\cdot \\frac{EMA(EMA(MOM, r), s)}{EMA(EMA(|MOM|, r), s)}',
      description: 'Smooth momentum oscillator designed to reduce noise and highlight trend momentum. Outputs TSI line and signal line.',
      library: 'pandas-ta (ta.tsi)',
      outputColumns: ['tsi_{fast}_{slow}_{signal}', 'tsis_{fast}_{slow}_{signal}'],
      defaultParams: 'fast = 13, slow = 25, signal = 13',
      interpretation: [
        'TSI > 0 → bullish momentum',
        'TSI < 0 → bearish momentum',
        'Signal line crossovers are common entry triggers',
        'Divergence with price indicates weakening trend',
      ],
      recommendedTimeframes: '1h–1D (excellent; moderate on 5m–15m)',
      dataNotes: [
        'Requires `slow + signal` warmup bars due to double smoothing',
      ],
      relatedIndicators: ['macd', 'rsi', 'roc'],
      panelType: 'sub-panel',
      quickWhy: 'Find the "Cleanest" possible trend without jagged price wiggles.',
      quickAnalogy: 'Noise-cancelling headphones. Blocks the background chatter so you only hear the main music of the stock.',
      quickImpact: 'Stays bullish/bearish longer, helping you avoid "Trading Too Much."',
      professionalRef: 'William Blau (1995)',
      timeframeBehavior: 'Significant impact from delay on double-smoothed values.',
    },
    {
      name: 'fisher',
      displayName: 'Fisher Transform',
      formulaLatex: 'x=0.33\\cdot 2\\cdot\\left(\\frac{C-\\min(C)}{\\max(C)-\\min(C)}-0.5\\right)+0.67x_{t-1}, \\quad Fisher = 0.5\\cdot \\ln\\left(\\frac{1+x}{1-x}\\right)',
      description: 'Converts price into a near-Gaussian distribution, amplifying turning points.',
      library: 'pandas-ta (ta.fisher)',
      outputColumns: ['fisher_{n}', 'fishers_{n}'],
      defaultParams: 'length = 9',
      interpretation: [
        'Fisher crossing above signal → bullish reversal',
        'Fisher crossing below signal → bearish reversal',
        'Often used for cycle detection',
        'Sharp peaks/troughs indicate strong turning points',
      ],
      recommendedTimeframes: '15m–4h (strong); too noisy on 1m–5m',
      dataNotes: [
        'Requires `length` warmup bars',
      ],
      relatedIndicators: ['stoch', 'rsi', 'willr'],
      panelType: 'sub-panel',
      quickWhy: 'Make "reversals" look like sharp spikes so you can\'t miss them.',
      quickAnalogy: 'A flat landscape where mountains (reversals) are hidden. Fisher turns them into giant, neon-lit towers.',
      quickImpact: 'Earliest warnings that a trend is about to end.',
      professionalRef: 'John Ehlers (2004)',
      timeframeBehavior: 'Dangerous with 15-minute delay as it is designed for "instant" turning points.',
    },
    {
      name: 'squeeze',
      displayName: 'Volatility Squeeze',
      formulaLatex: 'BB_{upper} < KC_{upper} \\;\\text{and}\\; BB_{lower} > KC_{lower} \\Rightarrow \\text{Squeeze ON}',
      description: 'Detects when Bollinger Bands contract inside Keltner Channels — a volatility compression phase that often precedes breakouts.',
      library: 'pandas-ta (ta.squeeze)',
      outputColumns: ['squeeze_{n}'],
      defaultParams: 'length = 20',
      interpretation: [
        'Squeeze ON → compression phase (low volatility)',
        'Squeeze OFF → expansion phase (breakout imminent)',
        'Best used with volume confirmation',
        'Direction of breakout determined by momentum at release',
      ],
      recommendedTimeframes: '15m–1D (excellent breakout detector on 4h–1D)',
      dataNotes: [
        'Requires stable volatility estimation',
        'Sensitive to missing candles and bad resampling',
      ],
      relatedIndicators: ['bbands', 'kc', 'atr'],
      panelType: 'sub-panel',
      quickWhy: 'Find the "Calm Before the Storm."',
      quickAnalogy: 'A coiled spring. The tighter you compress it, the further it flies when released (the breakout).',
      quickImpact: 'Tells you when the market is "resting" before a huge explosion.',
      professionalRef: 'John Carter',
      timeframeBehavior: 'Delay means you miss the first 15 minutes of the "Explosion."',
    },
  ];

  overlayIndicators = this.allIndicators.filter(i => i.panelType === 'overlay');
  subPanelIndicators = this.allIndicators.filter(i => i.panelType === 'sub-panel');

  csvBaseColumns = [
    { column: 'unix_ts', type: 'int', description: 'Unix timestamp in milliseconds (UTC)' },
    { column: 'iso_time', type: 'string', description: 'ISO 8601 datetime string (UTC)' },
    { column: 'open', type: 'float', description: 'Opening price of the minute bar' },
    { column: 'high', type: 'float', description: 'Highest price during the minute bar' },
    { column: 'low', type: 'float', description: 'Lowest price during the minute bar' },
    { column: 'close', type: 'float', description: 'Closing price of the minute bar' },
    { column: 'volume', type: 'float', description: 'Shares traded during the minute bar' },
    { column: 'vwap', type: 'float', description: 'Volume-weighted average price' },
    { column: 'transactions', type: 'int', description: 'Number of transactions' },
  ];

  validationNotes = [
    'All float values are rounded to 6 decimal places for consistency',
    'Empty cells represent NaN — indicator warm-up period or insufficient data',
    'Timestamps represent the start of each 1-minute bar (bar-open convention)',
    'Data is de-duplicated by timestamp and sorted chronologically',
    'Polygon returns consolidated tape data (not exchange-specific)',
    'Date range is chunked into ~111-day windows to stay within 50,000-bar API limit',
    'The metadata JSON file describes every column, its source, library, and parameters',
  ];

  dataCaveats = [
    { icon: 'pi-clock', label: 'Warmup Bars', text: 'Most indicators require `length` bars before producing valid values. Earlier rows will be NaN.' },
    { icon: 'pi-exclamation-triangle', label: 'Missing Bars', text: 'EMA-like indicators drift if missing candles exist in the data.' },
    { icon: 'pi-replay', label: 'Session Reset', text: 'VWAP must reset at session boundary (daily). Multi-day VWAP is not standard.' },
    { icon: 'pi-chart-bar', label: 'Volume Dependency', text: 'VWAP, AD, CMF, MFI, OBV require reliable volume data. Zero-volume bars make these indicators unreliable.' },
    { icon: 'pi-sync', label: 'Resampling', text: 'Ensure OHLCV resample logic is consistent with TradingView (especially volume aggregation).' },
    { icon: 'pi-moon', label: 'RTH vs Extended', text: 'Volume-based indicators behave very differently in extended hours due to thin volume.' },
  ];

  hasCriticalCaveat(ind: IndicatorDoc): boolean {
    return ind.dataNotes.some(n =>
      n.includes('Volume-dependent') ||
      n.includes('session boundary') ||
      n.includes('drift heavily') ||
      n.includes('extended hours')
    );
  }

  getDisplayName(name: string): string {
    const ind = this.allIndicators.find(i => i.name === name);
    return ind?.displayName ?? name.toUpperCase();
  }

  scrollToIndicator(name: string): void {
    const el = this.el.nativeElement.querySelector(`#ind-${name}`);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
}
