"""Regression coverage for the Signal Program build-receipt generator.

Issue #1728 / PRD S11.4: Start and Resume must load "a compatibility receipt
generated by the golden-trace qualification job," and "CI failure alone is
not an admission control." These tests prove the generator
(`scripts/run_signal_program_build_qualification.py`) is that job — not a
hand-maintained file — and that it fails closed rather than emitting
evidence for a program that no longer qualifies.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest
from pydantic import ValidationError

from app.engine.strategy.registry import _STRATEGY_REGISTRY
from app.services.signal_program_admission import (
    DEFAULT_QUALIFICATION_MANIFEST,
    ProgramBuildQualificationManifest,
    qualification_receipt_payload,
)
from scripts import run_signal_program_build_qualification as runner


@pytest.mark.slow
def test_generator_output_matches_committed_manifest_for_the_current_tree() -> None:
    """The round-trip contract: re-running the real golden-trace suite against the
    current tree reproduces the committed receipt file byte for byte.

    This is the mechanism that makes the acceptance criterion true — a program
    edit that changes behavior without bumping `program_version`/
    `golden_trace_root` changes the artifact digest but leaves the golden
    corpus trace roots stale, so the qualification suite this invokes
    (`test_ema_signal_program.py::test_validated_ema_settings_corpus_has_a_pinned_trace_root`)
    fails and `--check` below would too.
    """
    exit_code = runner.main(["--check"])

    assert exit_code == 0


def test_generator_refuses_to_write_a_receipt_when_qualification_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A failing golden-trace suite must abort before any file is touched.

    This is the fail-closed half of the acceptance criterion: a behavior
    change without the required program/root update produces a failing
    qualification suite (simulated here via a monkeypatched subprocess
    failure), and the generator must neither write a fresh manifest nor
    silently keep serving stale evidence for it.
    """
    monkeypatch.setattr(
        runner.subprocess,
        "run",
        lambda *_args, **_kwargs: subprocess.CompletedProcess(
            args=["pytest"],
            returncode=1,
            stdout="1 failed",
            stderr="trace root mismatch: golden corpus no longer reproduces the pinned root",
        ),
    )
    output_path = tmp_path / "signal_program_build_receipts.json"

    exit_code = runner.main(["--manifest-path", str(output_path)])

    assert exit_code == 1
    assert not output_path.exists()


def test_qualify_signal_program_builds_raises_and_reports_pytest_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        runner.subprocess,
        "run",
        lambda *_args, **_kwargs: subprocess.CompletedProcess(
            args=["pytest"], returncode=1, stdout="", stderr="assertion failed"
        ),
    )

    with pytest.raises(runner.QualificationFailedError, match="assertion failed"):
        runner.qualify_signal_program_builds(prior_receipts={}, fresh_qualified_at_ms=1)


def _written_manifest(tmp_path: Path, payload: dict) -> Path:
    path = tmp_path / "prior-build-receipts.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _ema_receipt(qualified_at_ms: int, git_provenance: dict | None = None) -> tuple[dict, str]:
    contract = _STRATEGY_REGISTRY["ema_crossover_signal"].signal_program_contract
    assert contract is not None
    suite = runner._QUALIFICATION_SUITES["ema_crossover_signal"]
    return (
        qualification_receipt_payload(
            program_key="ema_crossover_signal",
            contract=contract,
            qualified_at_ms=qualified_at_ms,
            qualification_suite=suite,
            git_provenance=git_provenance,
        ),
        suite,
    )


def test_reuses_qualified_at_ms_when_the_receipt_identity_is_unchanged(tmp_path: Path) -> None:
    committed_at_ms = 1_700_000_000_000
    receipt, suite = _ema_receipt(committed_at_ms)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_receipt_reuse(path)

    identity = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest=receipt["artifact_digest"],
        wiring_digest=receipt["wiring_digest"],
        qualification_suite=suite,
    )
    assert index[identity].qualified_at_ms == committed_at_ms


def test_mints_a_fresh_timestamp_when_the_artifact_digest_changed(tmp_path: Path) -> None:
    receipt, suite = _ema_receipt(1_700_000_000_000)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_receipt_reuse(path)

    changed = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest="f" * 64,  # simulates changed artifact bytes
        wiring_digest=receipt["wiring_digest"],
        qualification_suite=suite,
    )
    assert changed not in index


def test_mints_a_fresh_timestamp_when_only_the_wiring_changed(tmp_path: Path) -> None:
    """A wiring-only edit must re-date the receipt.

    ``wiring_digest`` is part of the qualified identity precisely so this
    cannot reuse the old timestamp: the receipt would otherwise attest to
    wiring bytes that did not exist when it claims they were qualified, and
    ``canary_admission`` persists that timestamp as activation evidence. This
    is the case that only appears *after* the initial v1 -> v2 migration,
    where the artifact half is untouched and the wiring half moves alone.
    """
    receipt, suite = _ema_receipt(1_700_000_000_000)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_receipt_reuse(path)

    wiring_moved = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest=receipt["artifact_digest"],
        wiring_digest="c" * 64,  # simulates an edited program factory
        qualification_suite=suite,
    )
    assert wiring_moved not in index


def test_a_manifest_from_another_schema_version_is_read_not_rejected(tmp_path: Path) -> None:
    """Reuse reads raw JSON, so writing a new receipt shape is never blocked by
    the old one. An unrecognised receipt simply does not match and mints a
    fresh timestamp, which is the safe direction."""
    receipt, _suite = _ema_receipt(1_700_000_000_000)
    alien = {key: value for key, value in receipt.items() if key != "wiring_digest"}
    path = _written_manifest(tmp_path, {"schema_version": 1, "receipts": [alien]})

    index = runner._prior_receipt_reuse(path)

    assert index == {}


def test_tampered_committed_receipt_fails_its_own_hash_self_check() -> None:
    """Mirrors `prove_running_program_build`'s fail-closed path at the schema layer:
    any byte-level tamper of a receipt breaks its self-consistency hash, which is
    exactly what turns a mismatched receipt into unreadable/invalid evidence
    instead of a silently accepted one.
    """
    manifest = ProgramBuildQualificationManifest.model_validate_json(
        DEFAULT_QUALIFICATION_MANIFEST.read_text(encoding="utf-8")
    )
    tampered = manifest.receipts[0].model_dump(mode="json")
    tampered["artifact_digest"] = "f" * 64

    with pytest.raises(ValidationError, match="qualification receipt hash does not match"):
        ProgramBuildQualificationManifest.model_validate({"schema_version": 1, "receipts": [tampered]})


_COMMITTED_PROVENANCE = {"commit_sha": "b" * 40, "dirty": False}
_CURRENT_PROVENANCE = {"commit_sha": "c" * 40, "dirty": True}


def _passing_subprocess(*_args: object, **_kwargs: object) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess(args=["pytest"], returncode=0, stdout="", stderr="")


def _qualified_ema_receipt(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    prior_manifest: dict | None,
) -> dict:
    """Run the full qualification assembly with suites and git state faked."""
    monkeypatch.setattr(runner.subprocess, "run", _passing_subprocess)
    monkeypatch.setattr(runner, "_current_git_provenance", lambda _paths: _CURRENT_PROVENANCE)
    prior_receipts: dict = {}
    if prior_manifest is not None:
        prior_receipts = runner._prior_receipt_reuse(_written_manifest(tmp_path, prior_manifest))

    manifest = runner.qualify_signal_program_builds(
        prior_receipts=prior_receipts,
        fresh_qualified_at_ms=1_700_000_000_555,
    )

    return next(
        receipt
        for receipt in manifest["receipts"]
        if receipt["program_key"] == "ema_crossover_signal"
    )


def test_reuses_git_provenance_with_the_timestamp_when_identity_is_unchanged(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An unchanged identity keeps its recorded provenance even when the repo
    has since moved on — re-running with unchanged code stays a byte-for-byte
    no-op, which is what keeps `--check` stable in CI regardless of the
    checkout's git state."""
    prior, _suite = _ema_receipt(1_700_000_000_000, git_provenance=_COMMITTED_PROVENANCE)

    receipt = _qualified_ema_receipt(
        tmp_path, monkeypatch, {"schema_version": 2, "receipts": [prior]}
    )

    assert receipt["qualified_at_ms"] == 1_700_000_000_000
    assert receipt["git_provenance"] == _COMMITTED_PROVENANCE


def test_backfills_git_provenance_when_the_prior_receipt_has_none(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A receipt minted before provenance existed gains it on the next run
    without being re-dated. The claim is about the bytes, not the original
    qualification event: the identity match just re-verified that the current
    tree still produces this exact artifact digest, so the current git state
    truthfully locates those bytes."""
    prior, _suite = _ema_receipt(1_700_000_000_000)

    receipt = _qualified_ema_receipt(
        tmp_path, monkeypatch, {"schema_version": 2, "receipts": [prior]}
    )

    assert receipt["qualified_at_ms"] == 1_700_000_000_000
    assert receipt["git_provenance"] == _CURRENT_PROVENANCE


def test_stamps_current_git_provenance_on_a_new_identity(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    receipt = _qualified_ema_receipt(tmp_path, monkeypatch, None)

    assert receipt["qualified_at_ms"] == 1_700_000_000_555
    assert receipt["git_provenance"] == _CURRENT_PROVENANCE


def test_receipts_omit_git_provenance_when_git_is_unavailable(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """No git on the path degrades to a receipt without lineage, never a
    failed qualification — provenance is recorded evidence, not a gate."""
    monkeypatch.setattr(runner.subprocess, "run", _passing_subprocess)
    monkeypatch.setattr(runner, "_current_git_provenance", lambda _paths: None)

    manifest = runner.qualify_signal_program_builds(
        prior_receipts={},
        fresh_qualified_at_ms=1_700_000_000_555,
    )

    assert all("git_provenance" not in receipt for receipt in manifest["receipts"])


def test_current_git_provenance_is_none_when_git_cannot_run(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _no_git(*_args: object, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        raise FileNotFoundError("git")

    monkeypatch.setattr(runner.subprocess, "run", _no_git)

    assert runner._current_git_provenance(("app/main.py",)) is None


def test_current_git_provenance_reads_the_paths_last_commit_and_dirtiness() -> None:
    """Against the real repo: the provenance of a committed, unmodified file
    is that file's last-touching commit with a clean flag."""
    provenance = runner._current_git_provenance(("app/main.py",))

    assert provenance is not None
    expected_sha = subprocess.run(
        ["git", "log", "-1", "--format=%H", "--", "app/main.py"],
        cwd=runner._SERVICE_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    assert provenance["commit_sha"] == expected_sha
    expected_dirty = bool(
        subprocess.run(
            ["git", "status", "--porcelain", "--", "app/main.py"],
            cwd=runner._SERVICE_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    )
    assert provenance["dirty"] is expected_dirty
