"""Regression coverage for the Signal Program build-receipt generator.

Issue #1728 / PRD S11.4: Start and Resume must load "a compatibility receipt
generated by the golden-trace qualification job," and "CI failure alone is
not an admission control." These tests prove the generator
(`scripts/run_signal_program_build_qualification.py`) is that job — not a
hand-maintained file — and that it fails closed rather than emitting
evidence for a program that no longer qualifies.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest
from pydantic import ValidationError

from app.engine.strategy.registry import _STRATEGY_REGISTRY
from app.services.signal_program_admission import (
    DEFAULT_QUALIFICATION_MANIFEST,
    ProgramBuildQualificationManifest,
    qualification_receipt_payload,
)
from scripts import run_signal_program_build_qualification as runner


@pytest.mark.slow
def test_generator_output_matches_committed_manifest_for_the_current_tree() -> None:
    """The round-trip contract: re-running the real golden-trace suite against the
    current tree reproduces the committed receipt file byte for byte.

    This is the mechanism that makes the acceptance criterion true — a program
    edit that changes behavior without bumping `program_version`/
    `golden_trace_root` changes the artifact digest but leaves the golden
    corpus trace roots stale, so the qualification suite this invokes
    (`test_ema_signal_program.py::test_validated_ema_settings_corpus_has_a_pinned_trace_root`)
    fails and `--check` below would too.
    """
    exit_code = runner.main(["--check"])

    assert exit_code == 0


def test_generator_refuses_to_write_a_receipt_when_qualification_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A failing golden-trace suite must abort before any file is touched.

    This is the fail-closed half of the acceptance criterion: a behavior
    change without the required program/root update produces a failing
    qualification suite (simulated here via a monkeypatched subprocess
    failure), and the generator must neither write a fresh manifest nor
    silently keep serving stale evidence for it.
    """
    monkeypatch.setattr(
        runner.subprocess,
        "run",
        lambda *_args, **_kwargs: subprocess.CompletedProcess(
            args=["pytest"],
            returncode=1,
            stdout="1 failed",
            stderr="trace root mismatch: golden corpus no longer reproduces the pinned root",
        ),
    )
    output_path = tmp_path / "signal_program_build_receipts.json"

    exit_code = runner.main(["--manifest-path", str(output_path)])

    assert exit_code == 1
    assert not output_path.exists()


def test_qualify_signal_program_builds_raises_and_reports_pytest_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        runner.subprocess,
        "run",
        lambda *_args, **_kwargs: subprocess.CompletedProcess(
            args=["pytest"], returncode=1, stdout="", stderr="assertion failed"
        ),
    )

    with pytest.raises(runner.QualificationFailedError, match="assertion failed"):
        runner.qualify_signal_program_builds(prior_qualified_at_ms={}, fresh_qualified_at_ms=1)


def _written_manifest(tmp_path: Path, payload: dict) -> Path:
    path = tmp_path / "prior-build-receipts.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _ema_receipt(qualified_at_ms: int) -> tuple[dict, str]:
    contract = _STRATEGY_REGISTRY["ema_crossover_signal"].signal_program_contract
    assert contract is not None
    suite = runner._QUALIFICATION_SUITES["ema_crossover_signal"]
    return (
        qualification_receipt_payload(
            program_key="ema_crossover_signal",
            contract=contract,
            qualified_at_ms=qualified_at_ms,
            qualification_suite=suite,
        ),
        suite,
    )


def test_reuses_qualified_at_ms_when_the_receipt_identity_is_unchanged(tmp_path: Path) -> None:
    committed_at_ms = 1_700_000_000_000
    receipt, suite = _ema_receipt(committed_at_ms)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_qualified_at_ms(path)

    identity = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest=receipt["artifact_digest"],
        wiring_digest=receipt["wiring_digest"],
        qualification_suite=suite,
    )
    assert index[identity] == committed_at_ms


def test_mints_a_fresh_timestamp_when_the_artifact_digest_changed(tmp_path: Path) -> None:
    receipt, suite = _ema_receipt(1_700_000_000_000)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_qualified_at_ms(path)

    changed = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest="f" * 64,  # simulates changed artifact bytes
        wiring_digest=receipt["wiring_digest"],
        qualification_suite=suite,
    )
    assert index.get(changed, 1_700_000_000_555) == 1_700_000_000_555


def test_mints_a_fresh_timestamp_when_only_the_wiring_changed(tmp_path: Path) -> None:
    """A wiring-only edit must re-date the receipt.

    ``wiring_digest`` is part of the qualified identity precisely so this
    cannot reuse the old timestamp: the receipt would otherwise attest to
    wiring bytes that did not exist when it claims they were qualified, and
    ``canary_admission`` persists that timestamp as activation evidence. This
    is the case that only appears *after* the initial v1 -> v2 migration,
    where the artifact half is untouched and the wiring half moves alone.
    """
    receipt, suite = _ema_receipt(1_700_000_000_000)
    path = _written_manifest(tmp_path, {"schema_version": 2, "receipts": [receipt]})

    index = runner._prior_qualified_at_ms(path)

    wiring_moved = runner._qualified_identity(
        program_key="ema_crossover_signal",
        program_version=receipt["program_version"],
        golden_trace_root=receipt["golden_trace_root"],
        artifact_digest=receipt["artifact_digest"],
        wiring_digest="c" * 64,  # simulates an edited program factory
        qualification_suite=suite,
    )
    assert index.get(wiring_moved, 1_700_000_000_555) == 1_700_000_000_555


def test_a_manifest_from_another_schema_version_is_read_not_rejected(tmp_path: Path) -> None:
    """Reuse reads raw JSON, so writing a new receipt shape is never blocked by
    the old one. An unrecognised receipt simply does not match and mints a
    fresh timestamp, which is the safe direction."""
    receipt, _suite = _ema_receipt(1_700_000_000_000)
    alien = {key: value for key, value in receipt.items() if key != "wiring_digest"}
    path = _written_manifest(tmp_path, {"schema_version": 1, "receipts": [alien]})

    index = runner._prior_qualified_at_ms(path)

    assert index == {}


def test_tampered_committed_receipt_fails_its_own_hash_self_check() -> None:
    """Mirrors `prove_running_program_build`'s fail-closed path at the schema layer:
    any byte-level tamper of a receipt breaks its self-consistency hash, which is
    exactly what turns a mismatched receipt into unreadable/invalid evidence
    instead of a silently accepted one.
    """
    manifest = ProgramBuildQualificationManifest.model_validate_json(
        DEFAULT_QUALIFICATION_MANIFEST.read_text(encoding="utf-8")
    )
    tampered = manifest.receipts[0].model_dump(mode="json")
    tampered["artifact_digest"] = "f" * 64

    with pytest.raises(ValidationError, match="qualification receipt hash does not match"):
        ProgramBuildQualificationManifest.model_validate({"schema_version": 1, "receipts": [tampered]})
